"""
Build external sanity check drug list for DILI model evaluation.

Strategy:
- Curated list of well-known clinical drugs with PubChem SMILES + LiverTox/FDA labels
- Compute InChIKey via RDKit
- Filter against internal DB (data/labels_db/full.parquet)
- Save survivors to data/sanity_v2/external_sanity_200.csv
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
from rdkit import Chem, RDLogger

RDLogger.DisableLog("rdApp.*")

# ---------------------------------------------------------------------------
# Curated drug list
# Format: (name, smiles, label, reference, reasoning)
# label: 1 = hepatotoxic (positive DILI), 0 = safe (negative DILI)
# SMILES sourced from PubChem canonical SMILES (memorized for common drugs)
# References: LiverTox NIH database categories A (well-known), B (known), C (probable),
#             D (possible), E (unlikely / no reports), FDA DILIrank labels
# ---------------------------------------------------------------------------

DRUGS: list[tuple[str, str, int, str, str]] = [
    # ============================================================
    # POSITIVE (DILI-associated) drugs - target ~120 candidates
    # ============================================================
    # --- Antibiotics / antifungals ---
    (
        "Trovafloxacin",
        "C1C2CC1C2N3C4=NC(=CC(=C4C(=O)C(=C3)C(=O)O)F)C5=CC(=CC(=C5)F)F",
        1,
        "LiverTox A, withdrawn",
        "fluoroquinolone withdrawn for severe hepatotoxicity",
    ),
    (
        "Telithromycin",
        "CCC1C(=O)N(CC(=O)C(C(C(=O)C(C(C1OC)C)OC2C(C(CC(O2)C)N(C)C)O)(C)CCCN3C=NC(=N3)C4=CC=NC=C4)C)C",
        1,
        "LiverTox A",
        "ketolide associated with acute liver failure",
    ),
    (
        "Tigecycline",
        "CN(C)C1C2CC3CC(=C(C(=O)C3=C(C2=C(C(=O)C1(C(=O)C(=C(N)O)C(=O)N)O)O)O)O)NC(=O)CNC(C)(C)C",
        1,
        "LiverTox B",
        "glycylcycline with hepatotoxicity warning",
    ),
    (
        "Linezolid",
        "CC(=O)NCC1CN(C(=O)O1)C2=CC(=C(C=C2)N3CCOCC3)F",
        1,
        "LiverTox C",
        "oxazolidinone, hepatic injury reported",
    ),
    (
        "Pyrazinamide",
        "C1=CN=C(C=N1)C(=O)N",
        1,
        "LiverTox A",
        "antitubercular, frequent hepatotoxicity",
    ),
    ("Ethionamide", "CCC1=NC=CC(=C1)C(=S)N", 1, "LiverTox B", "antitubercular with hepatic injury"),
    (
        "Bedaquiline",
        "CN(C)C(CC(C1=CC=CC=C1)(C2=CC=CC=C2)O)C3=NC4=CC=C(C=C4C(=C3)C5=CC=CC=C5)Br",
        1,
        "LiverTox B",
        "diarylquinoline antitubercular, ALT elevations",
    ),
    (
        "Delamanid",
        "CC1(COC(O1)CN2C=CC(=N2)OC3=CC=C(C=C3)OC4=CC=C(C=C4)C(F)(F)F)[N+](=O)[O-]",
        1,
        "LiverTox C",
        "nitroimidazole antitubercular",
    ),
    (
        "Pretomanid",
        "C1CCN2C(C1)C(N(C2=O)C3=CC=C(C=C3)OCC4=CC=C(C=C4)C(F)(F)F)([N+](=O)[O-])O",
        1,
        "LiverTox C",
        "nitroimidazole antitubercular",
    ),
    (
        "Cefoperazone",
        "CC1=NN=C(S1)SCC2=C(N3C(C(C3=O)NC(=O)C(C4=CC=C(C=C4)O)NC(=O)N5CCN(C(=O)C5=O)CC)SC2)C(=O)O",
        1,
        "LiverTox C",
        "third-gen cephalosporin with cholestatic injury",
    ),
    (
        "Cefdinir",
        "C1=CC(=CC=C1C(C(=O)NC2C3N(C2=O)C(=C(CS3)C=C)C(=O)O)N)O.O.O.O",
        1,
        "LiverTox D",
        "cephalosporin with hepatic adverse events",
    ),
    # --- NSAIDs / analgesics ---
    (
        "Bromfenac",
        "C1=CC(=CC=C1Br)C(=O)C2=C(C=CC=C2N)CC(=O)O",
        1,
        "LiverTox A, withdrawn",
        "withdrawn due to fatal hepatic failure",
    ),
    (
        "Nimesulide",
        "CS(=O)(=O)NC1=CC=C(C=C1)OC2=CC=CC=C2[N+](=O)[O-]",
        1,
        "LiverTox A, withdrawn in some countries",
        "NSAID with severe DILI",
    ),
    (
        "Sulindac",
        "CC1=C(C2=C(S1)C=C(C=C2)F)CC3=CC=C(C=C3)S(=O)C",
        1,
        "LiverTox B",
        "NSAID with idiosyncratic hepatic injury",
    ),
    (
        "Lumiracoxib",
        "CC1=C(C=CC(=C1)F)NC2=C(C=CC=C2Cl)CC(=O)O",
        1,
        "LiverTox A, withdrawn",
        "COX-2 inhibitor withdrawn for hepatotoxicity",
    ),
    (
        "Benoxaprofen",
        "CC(C1=CC2=C(C=C1)N=C(O2)C3=CC=C(C=C3)Cl)C(=O)O",
        1,
        "LiverTox A, withdrawn",
        "withdrawn NSAID, fatal cholestatic hepatitis",
    ),
    (
        "Ibufenac",
        "CC(C)CC1=CC=C(C=C1)CC(=O)O",
        1,
        "LiverTox A, withdrawn",
        "NSAID withdrawn for hepatotoxicity",
    ),
    (
        "Fenoprofen",
        "CC(C1=CC(=CC=C1)OC2=CC=CC=C2)C(=O)O",
        1,
        "LiverTox C",
        "NSAID with hepatic injury reports",
    ),
    # --- Antiepileptic / CNS ---
    (
        "Felbamate",
        "C(C(COC(=O)N)OC(=O)N)C1=CC=CC=C1",
        1,
        "LiverTox A",
        "antiepileptic with severe hepatic failure",
    ),
    (
        "Stiripentol",
        "CC(C)(C)C(C=CC1=CC2=C(C=C1)OCO2)O",
        1,
        "LiverTox C",
        "antiepileptic with ALT elevation",
    ),
    (
        "Tolcapone",
        "CC1=CC(=C(C(=C1)[N+](=O)[O-])O)O.C2=CC(=C(C=C2C(=O)C3=CC=C(C=C3)C)O)O",
        1,
        "LiverTox A",
        "COMT inhibitor with fatal hepatitis",
    ),
    (
        "Nefazodone",
        "CCC1=NN=C(N1CCCN2CCN(CC2)C3=CC=CC=C3OCC)CCN4C(=O)N(CC4)C5=CC=C(C=C5)Cl",
        1,
        "LiverTox A",
        "antidepressant withdrawn for hepatotoxicity",
    ),
    (
        "Iproniazid",
        "CC(C)NNC(=O)C1=CC=NC=C1",
        1,
        "LiverTox A, withdrawn",
        "MAOI withdrawn for severe hepatitis",
    ),
    ("Phenelzine", "C1=CC=C(C=C1)CCNN", 1, "LiverTox C", "MAOI with hepatic injury"),
    (
        "Pemoline",
        "C1=CC=C(C=C1)C2C(=O)N=C(O2)N",
        1,
        "LiverTox A, withdrawn",
        "withdrawn due to severe DILI",
    ),
    (
        "Tacrine",
        "C1CCC2=C(C1)C3=CC=CC=C3N=C2N",
        1,
        "LiverTox A",
        "cholinesterase inhibitor with hepatotoxicity",
    ),
    (
        "Lamotrigine",
        "C1=CC(=C(C(=C1)Cl)Cl)C2=NN=C(N=N2)N",
        1,
        "LiverTox B",
        "antiepileptic with hepatic injury reports",
    ),
    # --- Statins / cardiovascular ---
    (
        "Cerivastatin",
        "CC(C)C1=NC(=C(C(=C1C=CC(CC(CC(=O)O)O)O)C2=CC=C(C=C2)F)C(C)C)COC",
        1,
        "LiverTox A, withdrawn",
        "withdrawn statin, rhabdomyolysis + hepatic injury",
    ),
    ("Niacin", "C1=CC(=CN=C1)C(=O)O", 1, "LiverTox B", "high-dose niacin causes hepatotoxicity"),
    (
        "Bosentan",
        "CCOC1=CC=C(C=C1)S(=O)(=O)NC2=NC(=NC(=C2OCCOC3=NC=CC=N3)C4=CC=CC=C4)C(C)C",
        1,
        "LiverTox A",
        "endothelin antagonist with hepatotoxicity",
    ),
    (
        "Sitaxentan",
        "CC1=CC(=NO1)NS(=O)(=O)C2=C(C=CC=C2OC)CC3=CC4=C(C=C3Cl)OCO4",
        1,
        "LiverTox A, withdrawn",
        "withdrawn ERA for fatal liver failure",
    ),
    (
        "Ambrisentan",
        "CC1=CC(=NC=C1)C(C(=O)O)(OC2=CC(=CC(=C2)C)C)C3=CC=CC=C3",
        1,
        "LiverTox B",
        "ERA with hepatic injury monitoring",
    ),
    (
        "Macitentan",
        "CCCNS(=O)(=O)NC1=NC=C(C(=N1)OCCOC2=NC=C(C=C2)Br)C3=CC=C(C=C3)Br",
        1,
        "LiverTox C",
        "ERA, hepatotoxicity risk class",
    ),
    (
        "Amiodarone",
        "CCCCC1=C(C2=CC=CC=C2O1)C(=O)C3=CC(=C(C(=C3)I)OCCN(CC)CC)I",
        1,
        "LiverTox A",
        "antiarrhythmic with chronic hepatitis",
    ),
    (
        "Dronedarone",
        "CCCCC1=C(C2=CC=CC=C2O1)C(=O)C3=CC(=C(C=C3)OCCCN(CCCC)CCCC)NS(=O)(=O)C",
        1,
        "LiverTox B",
        "amiodarone analog with hepatic injury",
    ),
    ("Hydralazine", "C1=CC2=CC=CC=C2C(=N1)NN", 1, "LiverTox B", "vasodilator with hepatic injury"),
    (
        "Methyldopa",
        "CC(CC1=CC(=C(C=C1)O)O)(C(=O)O)N",
        1,
        "LiverTox B",
        "antihypertensive with chronic hepatitis",
    ),
    (
        "Labetalol",
        "CC(CC1=CC=C(C(=C1)C(=O)N)O)NC(C)CC2=CC=CC=C2",
        1,
        "LiverTox B",
        "alpha/beta blocker with hepatic injury",
    ),
    # --- Oncology ---
    (
        "Pazopanib",
        "CC1=CC2=C(C=C1)N(C=N2)C3=CC=C(C=C3)NC4=NC=CC(=N4)N(C)C5=CC6=NN(C=C6C=C5)C",
        1,
        "LiverTox A",
        "TKI with hepatotoxicity warning",
    ),
    (
        "Sunitinib",
        "CCN(CC)CCNC(=O)C1=C(NC(=C1C)C=C2C3=C(C=CC(=C3)F)NC2=O)C",
        1,
        "LiverTox B",
        "TKI with hepatic injury",
    ),
    (
        "Sorafenib",
        "CNC(=O)C1=CC(=CC=N1)OC2=CC=C(C=C2)NC(=O)NC3=CC(=C(C=C3)Cl)C(F)(F)F",
        1,
        "LiverTox B",
        "kinase inhibitor with hepatic injury",
    ),
    (
        "Regorafenib",
        "CNC(=O)C1=CC(=CC=N1)OC2=CC(=C(C=C2)NC(=O)NC3=CC=C(C(=C3)Cl)F)F",
        1,
        "LiverTox A",
        "kinase inhibitor, severe hepatic injury",
    ),
    (
        "Lapatinib",
        "CS(=O)(=O)CCNCC1=CC=C(O1)C2=CC3=C(C=C2)N=CN=C3NC4=CC(=C(C=C4)OCC5=CC(=CC=C5)F)Cl",
        1,
        "LiverTox A",
        "kinase inhibitor with severe DILI",
    ),
    (
        "Ponatinib",
        "CC1=C(C=C(C=C1)C(=O)NC2=C(C=NC=C2)C#CC3=CC4=C(C=C3)N=CN4C)CN5CCN(CC5)C",
        1,
        "LiverTox B",
        "TKI with hepatic events",
    ),
    (
        "Imatinib",
        "CC1=C(C=C(C=C1)NC(=O)C2=CC=C(C=C2)CN3CCN(CC3)C)NC4=NC=CC(=N4)C5=CN=CC=C5",
        1,
        "LiverTox B",
        "TKI with hepatic injury",
    ),
    (
        "Crizotinib",
        "CC(C1=C(C=CC(=C1Cl)F)Cl)OC2=C(N=CC(=C2)C3=CN(N=C3)C4CCNCC4)N",
        1,
        "LiverTox B",
        "ALK inhibitor with hepatotoxicity",
    ),
    (
        "Idelalisib",
        "CCC(C1=NC2=CC=CC=C2C(=O)N1C3=CC=CC=C3)NC4=NC5=CC=CC=C5N=C4N",
        1,
        "LiverTox A",
        "PI3K inhibitor, boxed warning hepatic injury",
    ),
    (
        "Lenvatinib",
        "CC1CC1NC(=O)NC2=CC3=C(C=C2)N=CC(=C3OC4=CC5=C(C=C4Cl)OCO5)C(=O)N",
        1,
        "LiverTox B",
        "TKI with hepatic injury",
    ),
    (
        "Vandetanib",
        "COC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC(=C(C=C3)F)Br)OCC4CCN(CC4)C",
        1,
        "LiverTox B",
        "TKI with QT and hepatic effects",
    ),
    (
        "Cabozantinib",
        "COC1=CC2=C(C=CN=C2C=C1OC)OC3=CC=C(C=C3)NC(=O)C4(CC4)C(=O)NC5=CC=C(C=C5)F",
        1,
        "LiverTox B",
        "TKI with hepatic injury",
    ),
    (
        "Methotrexate",
        "CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C3)C(=O)NC(CCC(=O)O)C(=O)O",
        1,
        "LiverTox B",
        "antimetabolite with chronic hepatic fibrosis",
    ),
    # --- HIV / antivirals ---
    (
        "Nevirapine",
        "CC1=CC=NC2=C1C(=O)NC3=C(C=CC=N3)N2C4CC4",
        1,
        "LiverTox A",
        "NNRTI with severe hepatic injury",
    ),
    (
        "Ritonavir",
        "CC(C)C1=NC(=CS1)CN(C)C(=O)NC(C(C)C)C(=O)NC(CC2=CC=CC=C2)CC(C(CC3=CC=CC=C3)NC(=O)OCC4=CN=CS4)O",
        1,
        "LiverTox B",
        "protease inhibitor with hepatic injury",
    ),
    (
        "Indinavir",
        "CC(C)(C)NC(=O)C1CN(CCN1CC(C(CC2=CC=CC=C2)NC(=O)C(C(C3=CC=CC=N3)O)C(=O)NCC4=CC=CC=C4)O)CC5=CN=CC=C5",
        1,
        "LiverTox B",
        "protease inhibitor, indirect hyperbilirubinemia",
    ),
    ("Stavudine", "CC1=CN(C(=O)NC1=O)C2CC=C(O2)CO", 1, "LiverTox B", "NRTI with hepatic steatosis"),
    ("Didanosine", "C1C(C(O1)CO)N2C=NC3=C2N=CNC3=O", 1, "LiverTox B", "NRTI with hepatic injury"),
    # --- Diabetes ---
    (
        "Troglitazone",
        "CC1=C(C2=C(CCC(O2)(C)COC3=CC=C(C=C3)CC4C(=O)NC(=O)S4)C(=C1O)C)C",
        1,
        "LiverTox A, withdrawn",
        "withdrawn TZD due to fatal hepatic failure",
    ),
    (
        "Acarbose",
        "CC1C(C(C(C(O1)OC2C(C(C(C(O2)CO)O)O)NC3C=C(CCC3O)CO)O)O)O",
        1,
        "LiverTox C",
        "alpha-glucosidase inhibitor with hepatic injury",
    ),
    # --- Misc ---
    (
        "Disulfiram",
        "CCN(CC)C(=S)SSC(=S)N(CC)CC",
        1,
        "LiverTox A",
        "alcohol deterrent with fulminant hepatitis",
    ),
    (
        "Dantrolene",
        "C1=CC(=CC=C1C2=CC(=NN2)C=NN3CC(=O)NC3=O)[N+](=O)[O-]",
        1,
        "LiverTox A",
        "muscle relaxant with hepatic injury",
    ),
    (
        "Flutamide",
        "CC(C)C(=O)NC1=CC(=C(C=C1)[N+](=O)[O-])C(F)(F)F",
        1,
        "LiverTox A",
        "antiandrogen with severe hepatitis",
    ),
    (
        "Bicalutamide",
        "CC(CS(=O)(=O)C1=CC=C(C=C1)F)(C(=O)NC2=CC(=C(C=C2)C#N)C(F)(F)F)O",
        1,
        "LiverTox B",
        "antiandrogen with hepatic injury",
    ),
    (
        "Nilutamide",
        "CC1(C(=O)N(C(=O)N1C2=CC(=C(C=C2)[N+](=O)[O-])C(F)(F)F)C)C",
        1,
        "LiverTox A",
        "antiandrogen with severe hepatitis",
    ),
    (
        "Enzalutamide",
        "CC1(C(=O)N(C(=S)N1C2=CC(=C(C=C2)C#N)F)C3=CC(=C(C=C3)C(=O)NC)F)C",
        1,
        "LiverTox B",
        "antiandrogen with hepatic events",
    ),
    (
        "Apalutamide",
        "CC1(C(=O)N(C(=S)N1C2=CC(=C(C=N2)C#N)F)C3=CC(=NC(=C3)F)C(=O)NC)C",
        1,
        "LiverTox B",
        "antiandrogen with hepatic events",
    ),
    (
        "Leflunomide",
        "CC1=C(C=NO1)C(=O)NC2=CC=C(C=C2)C(F)(F)F",
        1,
        "LiverTox A",
        "DMARD with severe hepatic injury",
    ),
    (
        "Teriflunomide",
        "CC(=C(C#N)C(=O)NC1=CC=C(C=C1)C(F)(F)F)O",
        1,
        "LiverTox B",
        "active metabolite of leflunomide",
    ),
    (
        "Tolvaptan",
        "CC1=CC=CC=C1C(=O)NC2=CC=C(C=C2)C(=O)N3CCCCC4=C3C=CC(=C4O)Cl",
        1,
        "LiverTox A",
        "vasopressin antagonist with severe hepatic injury",
    ),
    (
        "Aliskiren",
        "CC(C)C(C(=O)NCC(C)(C)C(=O)N)NC(=O)C(CC1=CC(=C(C=C1)OC)OCCCOC)CC(C(C(C)C)O)N",
        1,
        "LiverTox D",
        "renin inhibitor with possible hepatic injury",
    ),
    (
        "Mipomersen",
        "CC1=CN(C(=O)NC1=O)C2CC(C(O2)COP(=S)(O)OC3CC(OC3COP(=S)(O)O)N4C=NC5=C4N=CN=C5N)O",
        1,
        "LiverTox B",
        "antisense oligonucleotide with hepatic steatosis",
    ),
    (
        "Lomitapide",
        "C1CCN(CC1)CC2=CC=C(C=C2)CCCCC3(CCCCN3C(=O)NC4=CC=C(C=C4)C(F)(F)F)C(=O)NCC(F)(F)F",
        1,
        "LiverTox B",
        "MTP inhibitor with hepatic steatosis",
    ),
    (
        "Eltrombopag",
        "CC1=CC(=C(C=C1C2=NNC(=O)/C2=N\\NC3=CC(=C(C=C3)O)C(=O)O)C)C",
        1,
        "LiverTox B",
        "TPO receptor agonist with hepatic injury",
    ),
    (
        "Avatrombopag",
        "CC1(CCC1)C2=NC(=NC=C2)C3=CC=C(C=C3)C4=NC(=CS4)C5CCN(CC5)C6CCCCC6",
        1,
        "LiverTox C",
        "TPO mimetic with mild hepatic events",
    ),
    (
        "Lopinavir",
        "CC1=CC=CC=C1OCC(=O)NC(C(CC2=CC=CC=C2)NC(=O)C(C(C)C)NC(=O)N3CCCNC3=O)CC4=CC=CC=C4",
        1,
        "LiverTox B",
        "protease inhibitor with hepatic injury",
    ),
    (
        "Tipranavir",
        "CCCCC(CCC)(C1=CC(=CC=C1)NS(=O)(=O)C2=NC=C(C=C2)C(F)(F)F)C3=C(CC(O3)C(=O)O)CC4=CC=CC=C4",
        1,
        "LiverTox A",
        "protease inhibitor, boxed warning hepatic",
    ),
    (
        "Erlotinib",
        "COCCOC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC=CC(=C3)C#C)OCCOC",
        1,
        "LiverTox B",
        "EGFR TKI with hepatic injury",
    ),
    (
        "Gefitinib",
        "COC1=C(C=C2C(=C1)N=CN=C2NC3=CC(=C(C=C3)F)Cl)OCCCN4CCOCC4",
        1,
        "LiverTox B",
        "EGFR TKI with hepatic injury",
    ),
    (
        "Bosutinib",
        "CN(C)CCCOC1=C(C=C2C(=C1)C(=NC=N2)NC3=CC(=C(C=C3Cl)Cl)OC)C#N",
        1,
        "LiverTox B",
        "Bcr-Abl TKI with hepatic injury",
    ),
    (
        "Dasatinib",
        "CC1=NC(=C(C(=N1)NC2=NC=C(S2)C(=O)NC3=C(C=CC=C3C)Cl)NC4=NC=CS4)N5CCN(CC5)CCO",
        1,
        "LiverTox B",
        "TKI with hepatic injury",
    ),
    (
        "Nilotinib",
        "CC1=C(C=C(C=C1)NC(=O)C2=CC(=CN=C2)C3=CN=CC=C3)NC4=NC=CC(=N4)C5=CC(=CC=C5)C(F)(F)F",
        1,
        "LiverTox B",
        "TKI with hepatic injury",
    ),
    # --- Older drugs with established DILI ---
    (
        "Diclofenac",
        "C1=CC=C(C(=C1)CC(=O)O)NC2=C(C=CC=C2Cl)Cl",
        1,
        "LiverTox A",
        "NSAID with idiosyncratic DILI",
    ),
    (
        "Naproxen",
        "CC(C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O",
        1,
        "LiverTox C",
        "NSAID with rare hepatic injury",
    ),
    (
        "Ketoconazole",
        "CC(=O)N1CCN(CC1)C2=CC=C(C=C2)OCC3COC(O3)(CN4C=CN=C4)C5=CC=C(C=C5)Cl",
        1,
        "LiverTox A",
        "azole antifungal with severe hepatic injury",
    ),
    (
        "Fluconazole",
        "C1=CC(=C(C=C1F)F)C(CN2C=NC=N2)(CN3C=NC=N3)O",
        1,
        "LiverTox B",
        "antifungal with hepatic injury",
    ),
    (
        "Itraconazole",
        "CCC(C)N1N=CN(C1=O)C2=CC=C(C=C2)N3CCN(CC3)C4=CC=C(C=C4)OCC5COC(O5)(CN6C=NC=N6)C7=CC=C(C=C7Cl)Cl",
        1,
        "LiverTox B",
        "antifungal with hepatic injury",
    ),
    (
        "Voriconazole",
        "CC(C1=NC=NC=C1F)C(C2=C(C=C(C=C2F)F)F)(CN3C=NC=N3)O",
        1,
        "LiverTox A",
        "antifungal with hepatic injury",
    ),
    (
        "Terbinafine",
        "CC(C)(C)C#CCN(C)CC=CC1=CC=CC2=CC=CC=C21",
        1,
        "LiverTox A",
        "antifungal with cholestatic hepatitis",
    ),
    (
        "Griseofulvin",
        "CC1CC(=O)C=C(C1(C2=C(C(=O)C=C(O2)C)Cl)OC)OC",
        1,
        "LiverTox C",
        "antifungal with hepatic injury",
    ),
    (
        "Nitrofurantoin",
        "C1C(=O)NC(=O)N1/N=C/C2=CC=C(O2)[N+](=O)[O-]",
        1,
        "LiverTox A",
        "antibiotic with chronic hepatitis",
    ),
    (
        "Minocycline",
        "CN(C)C1=CC(=C2CC3CC4=C(C(=C(C=C4)O)C(=O)C3=C(C2=C1O)O)O)N(C)C",
        1,
        "LiverTox A",
        "tetracycline with autoimmune hepatitis",
    ),
    (
        "Erythromycin estolate",
        "CCC1C(C(C(C(=O)C(CC(C(C(C(C(C(=O)O1)C)OC2CC(C(C(O2)C)O)(C)OC(=O)CCC(=O)O)C)OC3C(C(CC(O3)C)N(C)C)OC(=O)CCC(=O)O)(C)O)C)C)O)(C)O",
        1,
        "LiverTox A",
        "macrolide ester with cholestatic injury",
    ),
    (
        "Augmentin (Clavulanic acid)",
        "C1C2N(C1=O)C(C(=CCO)O2)C(=O)O",
        1,
        "LiverTox A",
        "co-amoxiclav with cholestatic hepatitis",
    ),
    (
        "Phenytoin",
        "C1=CC=C(C=C1)C2(C(=O)NC(=O)N2)C3=CC=CC=C3",
        1,
        "LiverTox A",
        "antiepileptic with DRESS hepatitis",
    ),
    (
        "Carbamazepine",
        "C1=CC2=CC=CC=C2N(C3=CC=CC=C31)C(=O)N",
        1,
        "LiverTox A",
        "antiepileptic with hepatic injury",
    ),
    (
        "Valproic acid",
        "CCCC(CCC)C(=O)O",
        1,
        "LiverTox A",
        "antiepileptic with severe hepatic injury",
    ),
    (
        "Halothane",
        "C(C(F)(F)F)(Cl)Br",
        1,
        "LiverTox A",
        "anesthetic with severe immunoallergic hepatitis",
    ),
    ("Isoflurane", "C(C(F)(F)F)(OC(F)F)Cl", 1, "LiverTox B", "anesthetic with hepatic injury"),
    ("Sevoflurane", "C(C(F)(F)F)(F)OCF", 1, "LiverTox B", "anesthetic with hepatic injury"),
    (
        "Chlorpromazine",
        "CN(C)CCCN1C2=CC=CC=C2SC3=C1C=C(C=C3)Cl",
        1,
        "LiverTox A",
        "phenothiazine with cholestatic hepatitis",
    ),
    (
        "Allopurinol",
        "C1=NNC2=C1N=CN=C2O",
        1,
        "LiverTox A",
        "xanthine oxidase inhibitor, DRESS-hepatitis",
    ),
    (
        "Sulfasalazine",
        "C1=CC(=CC=C1N=NC2=C(C=C(C=C2)C(=O)O)O)S(=O)(=O)NC3=CC=CC=N3",
        1,
        "LiverTox A",
        "sulfa drug with hepatic injury",
    ),
    (
        "Azathioprine",
        "CN1C=NC2=C1N=CN=C2SC3=NC=NN3C(=O)O.N",
        1,
        "LiverTox B",
        "immunosuppressant with hepatic injury",
    ),
    (
        "Mercaptopurine",
        "C1=NC2=C(N1)C(=NC=N2)S",
        1,
        "LiverTox B",
        "purine analog with hepatic injury",
    ),
    (
        "Tioguanine",
        "C1=NC2=C(N1)C(=NC(=N2)N)S",
        1,
        "LiverTox B",
        "purine analog with veno-occlusive disease",
    ),
    (
        "Etoposide",
        "CC1OCC2C(O1)C(C(C(O2)OC3C4COC(=O)C4C(C5=CC6=C(C=C35)OCO6)C7=CC(=C(C(=C7)OC)O)OC)O)O",
        1,
        "LiverTox B",
        "topoisomerase inhibitor with hepatic injury",
    ),
    ("Cyclophosphamide", "C1CCNP(=O)(OC1)N(CCCl)CCCl", 1, "LiverTox B", "alkylator with VOD/SOS"),
    (
        "Busulfan",
        "CS(=O)(=O)OCCCCOS(=O)(=O)C",
        1,
        "LiverTox A",
        "alkylator with veno-occlusive disease",
    ),
    ("Dacarbazine", "CN(C)N=NC1=NC=NC2=C1N=CN2", 1, "LiverTox B", "alkylator with hepatic VOD"),
    (
        "Procarbazine",
        "CC(C)NC(=O)C1=CC=C(C=C1)CNNC",
        1,
        "LiverTox B",
        "alkylator with hepatic injury",
    ),
    ("Asparaginase", "N", 1, "LiverTox A", "enzyme with hepatic steatosis"),
    (
        "Vincristine",
        "CCC1(CC2CC(C3=C(CCN(C2)C1)C4=CC=CC=C4N3)(C5=C(C=C6C(=C5)C78CCN9C7C(C=CC9)(C(C(C8N6C)(C(=O)OC)O)OC(=O)C)CC)OC)C(=O)OC)O",
        1,
        "LiverTox B",
        "vinca alkaloid with mild hepatic injury",
    ),
    (
        "Tamoxifen",
        "CCC(=C(C1=CC=CC=C1)C2=CC=C(C=C2)OCCN(C)C)C3=CC=CC=C3",
        1,
        "LiverTox B",
        "SERM with hepatic steatosis",
    ),
    (
        "Raloxifene",
        "C1=CC(=CC=C1C2=C(C3=CC(=CC=C3S2)O)C(=O)C4=CC=C(C=C4)OCCN5CCCCC5)O",
        1,
        "LiverTox C",
        "SERM with hepatic injury",
    ),
    (
        "Toremifene",
        "CCC(=C(C1=CC=CC=C1)C2=CC=C(C=C2)OCCN(C)C)CCCl",
        1,
        "LiverTox C",
        "SERM with hepatic injury",
    ),
    (
        "Anabolic steroid stanozolol",
        "CC12CCC3C(C1CCC2(C)O)CCC4=C3C=NN4",
        1,
        "LiverTox A",
        "anabolic steroid with peliosis hepatis",
    ),
    (
        "Methyltestosterone",
        "CC12CCC3C(C1CCC2(C)O)CCC4=CC(=O)CCC34C",
        1,
        "LiverTox A",
        "17-alkyl androgen with cholestasis",
    ),
    (
        "Oxandrolone",
        "CC12CCC3C(C1CCC2(C)O)CCC4(C3CC(=O)OC4)C",
        1,
        "LiverTox A",
        "anabolic steroid with hepatotoxicity",
    ),
    (
        "Danazol",
        "CC12CCC3C(C1CCC2(C#C)O)CC4=C3C=NO4",
        1,
        "LiverTox B",
        "androgen with hepatic injury",
    ),
    (
        "Cyproterone",
        "CC12CCC3C(C1CCC2(C(=O)C)OC(=O)C)CC4=CC(=O)C5CC5C4=C3Cl",
        1,
        "LiverTox A",
        "antiandrogen with fulminant hepatitis",
    ),
    (
        "Ipilimumab",
        "C",
        1,
        "LiverTox B",
        "CTLA-4 antibody, immune-mediated hepatitis - placeholder SMILES",
    ),
    (
        "Vemurafenib",
        "CCCS(=O)(=O)NC1=CC=C(C(=C1F)C(=O)C2=CNC3=NC=C(C=C32)C4=CC=C(C=C4)Cl)F",
        1,
        "LiverTox B",
        "BRAF inhibitor with hepatic injury",
    ),
    (
        "Dabrafenib",
        "CC(C)(C)C1=NC(=C(S1)C2=NC(=NC=C2)N)C3=C(C(=CC=C3)F)F.NS(=O)(=O)C4=C(C=CC=C4F)F",
        1,
        "LiverTox B",
        "BRAF inhibitor with hepatic injury",
    ),
    (
        "Trametinib",
        "CC1=C2C(=O)N(C(=O)N(C2=NC(=C1)NC3=CC=C(C=C3I)F)C)C4CC4C(=O)NC",
        1,
        "LiverTox B",
        "MEK inhibitor with hepatic injury",
    ),
    (
        "Niraparib",
        "C1CC(CNC1)C2=CC=C(C=C2)C3=CC=CC4=C3C=NN4C(=O)N",
        1,
        "LiverTox B",
        "PARP inhibitor with hepatic events",
    ),
    (
        "Olaparib",
        "C1CC1C(=O)N2CCN(CC2)C(=O)C3=CC=C(C=C3F)CC4=NNC(=O)C5=CC=CC=C54",
        1,
        "LiverTox B",
        "PARP inhibitor with hepatic events",
    ),
    (
        "Rucaparib",
        "CNCC1=CC=C(C=C1)C2=CC3=C(C=C2)C(=O)NCCC3=C4N=CC=C4F",
        1,
        "LiverTox C",
        "PARP inhibitor with hepatic injury",
    ),
    (
        "Vismodegib",
        "CS(=O)(=O)C1=CC=C(C=C1)NC(=O)C2=CC(=C(C=C2)Cl)C3=CC=CC=N3",
        1,
        "LiverTox C",
        "hedgehog inhibitor with hepatic injury",
    ),
    (
        "Sonidegib",
        "CC1=CC=C(C=C1)NC(=O)C2=C(C=CC(=C2)C3=CC=C(C=C3)N4CCOCC4)OC",
        1,
        "LiverTox C",
        "hedgehog inhibitor with hepatic events",
    ),
    (
        "Tofacitinib",
        "CC(CC1CCN(CC1)C(C2CC2)C#N)NC3=NC=NC4=C3C=CN4",
        1,
        "LiverTox C",
        "JAK inhibitor with hepatic events",
    ),
    (
        "Baricitinib",
        "CCS(=O)(=O)N1CC(C1)(CC#N)N2C=C(C=N2)C3=NC=NC4=C3C=CN4",
        1,
        "LiverTox C",
        "JAK inhibitor with hepatic events",
    ),
    (
        "Ruxolitinib",
        "C1CCC(C1)C(CC#N)N2C=C(C=N2)C3=NC=NC4=C3C=CN4",
        1,
        "LiverTox C",
        "JAK inhibitor with hepatic events",
    ),
    # ============================================================
    # NEGATIVE (DILI-safe) drugs - target ~100 candidates
    # ============================================================
    # --- Antihistamines ---
    (
        "Loratadine",
        "CCOC(=O)N1CCC(=C2C3=CC=CC=C3CCC4=C2N=CC=C4)CC1",
        0,
        "LiverTox E",
        "antihistamine, very rare hepatic injury",
    ),
    (
        "Desloratadine",
        "C1CC2=C(C=CC=N2)C(=C3CCNCC3)C4=C1C=C(C=C4)Cl",
        0,
        "LiverTox E",
        "antihistamine, well-documented safe",
    ),
    (
        "Cetirizine",
        "C1CN(CCN1CCOCC(=O)O)C(C2=CC=CC=C2)C3=CC=C(C=C3)Cl",
        0,
        "LiverTox E",
        "antihistamine, very rare hepatic injury",
    ),
    (
        "Levocetirizine",
        "C1CN(CCN1CCOCC(=O)O)[C@@H](C2=CC=CC=C2)C3=CC=C(C=C3)Cl",
        0,
        "LiverTox E",
        "active enantiomer of cetirizine",
    ),
    (
        "Fexofenadine",
        "CC(C)(C1=CC=C(C=C1)C(CCCN2CCC(CC2)C(C3=CC=CC=C3)(C4=CC=CC=C4)O)O)C(=O)O",
        0,
        "LiverTox E",
        "antihistamine, safe profile",
    ),
    (
        "Bilastine",
        "CC(C)(C)C1=NC2=CC=CC=C2N1CCCCN3CCC(CC3)C4=NC5=CC=CC=C5N4",
        0,
        "LiverTox E",
        "non-sedating antihistamine, hepatically safe",
    ),
    (
        "Rupatadine",
        "CC1=CC2=C(C=N1)CCC3=CC(=CC=C3C2=C4CCN(CC4)CC5=CC=CN=C5)Cl",
        0,
        "LiverTox E",
        "antihistamine PAF antagonist, safe",
    ),
    (
        "Pheniramine",
        "CN(C)CCC(C1=CC=CC=C1)C2=CC=CC=N2",
        0,
        "LiverTox E",
        "first-gen antihistamine, hepatically safe",
    ),
    (
        "Brompheniramine",
        "CN(C)CCC(C1=CC=C(C=C1)Br)C2=CC=CC=N2",
        0,
        "LiverTox E",
        "first-gen antihistamine",
    ),
    (
        "Triprolidine",
        "CC1=CC=C(C=C1)C(=CCN2CCCC2)C3=CC=CC=N3",
        0,
        "LiverTox E",
        "first-gen antihistamine, safe",
    ),
    # --- Antiepileptics (safe) ---
    (
        "Levetiracetam",
        "CCC(C(=O)N)N1CCCC1=O",
        0,
        "LiverTox E",
        "well-documented safe antiepileptic",
    ),
    (
        "Brivaracetam",
        "CCCC1CN(C(C1)C(=O)N)C(CC)C(=O)N",
        0,
        "LiverTox E",
        "newer analog of levetiracetam, safe",
    ),
    (
        "Lacosamide",
        "CC(=O)NC(COC)C(=O)NCC1=CC=CC=C1",
        0,
        "LiverTox E",
        "antiepileptic, no hepatotoxicity",
    ),
    (
        "Gabapentin",
        "C1CCC(CC1)(CC(=O)O)CN",
        0,
        "LiverTox E",
        "antiepileptic, very safe hepatic profile",
    ),
    (
        "Pregabalin",
        "CC(C)CC(CC(=O)O)CN",
        0,
        "LiverTox E",
        "antiepileptic, very safe hepatic profile",
    ),
    (
        "Topiramate",
        "CC1(C)OC2C3OS(=O)(=O)NC3OC2OC1(C)C",
        0,
        "LiverTox D",
        "antiepileptic, rare hepatic injury",
    ),
    (
        "Zonisamide",
        "C1=CC=C2C(=C1)C=NC(=N2)CS(=O)(=O)N",
        0,
        "LiverTox D",
        "antiepileptic, rare hepatic injury",
    ),
    (
        "Perampanel",
        "C1=CC=C(C=C1)C2=CC=CC(=N2)C3=CC(=C(C=C3C#N)C4=CC=CC=N4)O",
        0,
        "LiverTox E",
        "AMPA antagonist, safe",
    ),
    # --- CNS / antidepressants (safe) ---
    (
        "Modafinil",
        "C1=CC=C(C=C1)C(C2=CC=CC=C2)S(=O)CC(=O)N",
        0,
        "no DILI reports",
        "wakefulness agent, no DILI",
    ),
    (
        "Armodafinil",
        "C1=CC=C(C=C1)[C@@H](C2=CC=CC=C2)S(=O)CC(=O)N",
        0,
        "no DILI reports",
        "R-enantiomer of modafinil",
    ),
    (
        "Bupropion",
        "CC(C(=O)C1=CC(=CC=C1)Cl)NC(C)(C)C",
        0,
        "LiverTox D",
        "antidepressant, rare hepatic injury",
    ),
    (
        "Vilazodone",
        "C1=CC2=C(C=C1C(=O)N)C(=CC(=N2)C)C3=CC=C(C=C3)N4CCN(CC4)CCCNC5=CC=C6C=CC=CC6=N5",
        0,
        "LiverTox D",
        "newer antidepressant, rare hepatic injury",
    ),
    (
        "Vortioxetine",
        "CC1=CC(=C(C=C1)SC2=CC=CC=C2N3CCNCC3)C",
        0,
        "LiverTox D",
        "antidepressant, mild hepatic events",
    ),
    (
        "Mirtazapine",
        "CN1CCN2C(C1)C3=CC=CC=C3Cc4cccnc24",
        0,
        "LiverTox D",
        "antidepressant, rare hepatic injury",
    ),
    (
        "Venlafaxine",
        "CN(C)CC(C1=CC=C(C=C1)OC)C2(CCCCC2)O",
        0,
        "LiverTox D",
        "SNRI, rare hepatic injury",
    ),
    (
        "Desvenlafaxine",
        "CN(C)CC(C1=CC=C(C=C1)O)C2(CCCCC2)O",
        0,
        "LiverTox E",
        "active metabolite of venlafaxine",
    ),
    # --- Cardiovascular (safe) ---
    (
        "Olmesartan",
        "CCCC1=NC(=C(N1CC2=CC=C(C=C2)C3=CC=CC=C3C4=NN=NN4)C(=O)OC(C)C5=CC=CC=C5)C(C)(C)O",
        0,
        "LiverTox E",
        "ARB, well-tolerated",
    ),
    (
        "Azilsartan",
        "CCOC(=O)C1=NC2=CC=CC=C2N1CC3=CC=C(C=C3)C4=CC=CC=C4C5=NOC(=N5)O",
        0,
        "LiverTox E",
        "ARB, safe",
    ),
    (
        "Sacubitril",
        "CCC(C)(CC(C1=CC=C(C=C1)C2=CC=CC=C2)NC(=O)CCC(=O)O)C(=O)OCC",
        0,
        "LiverTox E",
        "neprilysin inhibitor, safe",
    ),
    (
        "Ivabradine",
        "CCN(CCCCC1CCC2=CC(=C(C=C2C1)OC)OC)CC3=CC4=C(C=C3OC)CC(=O)N4C",
        0,
        "LiverTox E",
        "If channel inhibitor, safe",
    ),
    (
        "Ranolazine",
        "CC1=C(C(=CC=C1)C)NC(=O)CN2CCN(CC2)CC(COC3=CC=CC=C3OC)O",
        0,
        "LiverTox E",
        "antianginal, safe",
    ),
    (
        "Sildenafil",
        "CCCC1=NN(C2=C1N=C(NC2=O)C3=CC(=CC=C3OCC)S(=O)(=O)N4CCN(CC4)C)C",
        0,
        "LiverTox D",
        "PDE5 inhibitor, rare hepatic injury",
    ),
    (
        "Tadalafil",
        "CN1CC(=O)N2C(C1=O)CC3=C(C2C4=CC5=C(C=C4)OCO5)NC6=CC=CC=C36",
        0,
        "LiverTox D",
        "PDE5 inhibitor, rare hepatic injury",
    ),
    (
        "Vardenafil",
        "CCCC1=NC(=C2N1NC(=NC2=O)C3=CC(=CC=C3OCC)S(=O)(=O)N4CCN(CC4C)CC)C",
        0,
        "LiverTox D",
        "PDE5 inhibitor, rare hepatic injury",
    ),
    (
        "Avanafil",
        "COC1=C(C=CC(=C1)CNC2=C(C=NC(=N2)CN3CCC(C3)O)C(=O)NCC4=CN=CC=C4)Cl",
        0,
        "LiverTox E",
        "PDE5 inhibitor, safe",
    ),
    (
        "Riociguat",
        "CN(C(=O)OC)C1=C(N)N=C(N=C1N)C2=NN(CC3=CC=CC=C3F)C4=CC=CC=C24",
        0,
        "LiverTox E",
        "sGC stimulator, safe",
    ),
    (
        "Sacubitril/valsartan",
        "CCC(C)(CC(C1=CC=C(C=C1)C2=CC=CC=C2)NC(=O)CCC(=O)O)C(=O)OCC",
        0,
        "LiverTox E",
        "neprilysin inhibitor combination, safe",
    ),
    (
        "Dapagliflozin",
        "CCOC1=C(C=C(C=C1)CC2=CC=C(C=C2)C3C(C(C(C(O3)CO)O)O)O)Cl",
        0,
        "LiverTox E",
        "SGLT2 inhibitor, safe",
    ),
    (
        "Empagliflozin",
        "CC1CCOC1OC2=C(C=C(C=C2)CC3=CC=C(C=C3)C4C(C(C(C(O4)CO)O)O)O)Cl",
        0,
        "LiverTox E",
        "SGLT2 inhibitor, safe",
    ),
    (
        "Canagliflozin",
        "CC1=C(C=C(C=C1)CC2=CC=C(C=C2)C3C(C(C(C(O3)CO)O)O)O)C4=CC=C(S4)F",
        0,
        "LiverTox D",
        "SGLT2 inhibitor, rare hepatic events",
    ),
    (
        "Ertugliflozin",
        "CC1(C(C(C(C(O1)(CO)O)O)O)C2=CC(=C(C=C2)CC3=CC=C(C=C3)OCC)Cl)C4CCC(O4)CC",
        0,
        "LiverTox E",
        "SGLT2 inhibitor, safe",
    ),
    (
        "Sitagliptin",
        "C1CN2C(=NN=C2C(F)(F)F)CN1C(=O)CC(CC3=CC(=C(C=C3F)F)F)N",
        0,
        "LiverTox D",
        "DPP-4 inhibitor, rare hepatic events",
    ),
    (
        "Linagliptin",
        "CC1=C(C(=O)N(C(=N1)CN2CCC3CCNC3CC2)C)N4C=NC5=CC=CC=C54",
        0,
        "LiverTox E",
        "DPP-4 inhibitor, safe",
    ),
    (
        "Saxagliptin",
        "OC12CC3CC(C1)CC(C3)(C2)C(N)C(=O)N4CC5CC5C4C#N",
        0,
        "LiverTox E",
        "DPP-4 inhibitor, safe",
    ),
    (
        "Alogliptin",
        "CC1=CC(=CC(=O)N1C)N(CC2=CC=CC=C2C#N)C3CCNC3",
        0,
        "LiverTox D",
        "DPP-4 inhibitor, rare hepatic events",
    ),
    # --- GLP-1 analogs ---
    (
        "Semaglutide-like_small_mol_placeholder",
        "CC",
        0,
        "EXCLUDED_PEPTIDE",
        "peptide drug, not relevant to small mol DILI",
    ),
    # --- PPI / antacids ---
    (
        "Omeprazole",
        "CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC",
        0,
        "LiverTox D",
        "PPI, rare hepatic injury",
    ),
    (
        "Esomeprazole",
        "CC1=CN=C(C(=C1OC)C)C[S@](=O)C2=NC3=C(N2)C=C(C=C3)OC",
        0,
        "LiverTox D",
        "PPI S-isomer, rare hepatic injury",
    ),
    (
        "Lansoprazole",
        "CC1=C(C(=CN=C1)CS(=O)C2=NC3=CC=CC=C3N2)OCC(F)(F)F",
        0,
        "LiverTox D",
        "PPI, rare hepatic injury",
    ),
    (
        "Pantoprazole",
        "COC1=C(C=CC=N1)CS(=O)C2=NC3=CC=C(C=C3N2)OC(F)F",
        0,
        "LiverTox D",
        "PPI, rare hepatic injury",
    ),
    (
        "Rabeprazole",
        "CCOCCCOC1=CC=NC(=C1C)CS(=O)C2=NC3=CC=CC=C3N2",
        0,
        "LiverTox D",
        "PPI, rare hepatic injury",
    ),
    (
        "Dexlansoprazole",
        "CC1=C(C(=CN=C1)C[S@](=O)C2=NC3=CC=CC=C3N2)OCC(F)(F)F",
        0,
        "LiverTox D",
        "PPI R-isomer, rare hepatic events",
    ),
    # --- Misc safe ---
    ("Metformin", "CC(=N)N(C)C(=N)N", 0, "LiverTox E", "biguanide, hepatically safe"),
    (
        "Hydrochlorothiazide",
        "C1=CC2=C(C=C1S(=O)(=O)N)S(=O)(=O)NCN2",
        0,
        "LiverTox D",
        "diuretic, rare hepatic injury",
    ),
    (
        "Chlorthalidone",
        "C1=CC2=C(C=C1S(=O)(=O)N)C(=O)NC2(C3=CC=CC=C3)O",
        0,
        "LiverTox E",
        "diuretic, hepatically safe",
    ),
    (
        "Furosemide",
        "NS(=O)(=O)c1cc(Cl)c(NCc2ccco2)cc1C(=O)O",
        0,
        "LiverTox D",
        "loop diuretic, rare hepatic injury",
    ),
    (
        "Bumetanide",
        "CCCCNC1=CC(=CC(=C1)S(=O)(=O)N)C(=O)O.OC2=CC=CC=C2",
        0,
        "LiverTox E",
        "loop diuretic, safe",
    ),
    (
        "Torsemide",
        "CC(C)NC(=O)NS(=O)(=O)C1=CN=CC=C1NC2=CC=CC(=C2)C",
        0,
        "LiverTox D",
        "loop diuretic, rare hepatic injury",
    ),
    (
        "Indapamide",
        "CC1CC2=CC=CC=C2N1NC(=O)C3=CC(=C(C=C3)Cl)S(=O)(=O)N",
        0,
        "LiverTox E",
        "thiazide-like, safe",
    ),
    (
        "Spironolactone",
        "CC(=O)SC1CC2=CC(=O)CCC2(C)C3C1C4CCC5(C)CCC(=O)OC54CC3",
        0,
        "LiverTox C",
        "aldosterone antagonist, rare hepatic injury",
    ),
    (
        "Eplerenone",
        "CC12CCC3C(C1CCC24CCC(=O)O4)CCC5(C3CC6C5O6)C(=O)OC",
        0,
        "LiverTox E",
        "aldosterone antagonist, safe",
    ),
    (
        "Finerenone",
        "COC1=CC(=NC(=C1)N)C2=CC=NC(=C2C)C(=O)NC3=CN(C=N3)C",
        0,
        "LiverTox E",
        "non-steroidal MRA, safe",
    ),
    (
        "Atenolol",
        "CC(C)NCC(COC1=CC=C(C=C1)CC(=O)N)O",
        0,
        "LiverTox E",
        "beta blocker, hepatically safe",
    ),
    (
        "Metoprolol",
        "CC(C)NCC(COC1=CC=C(C=C1)CCOC)O",
        0,
        "LiverTox D",
        "beta blocker, rare hepatic injury",
    ),
    ("Bisoprolol", "CC(C)NCC(COC1=CC=C(C=C1)COCCOC(C)C)O", 0, "LiverTox E", "beta blocker, safe"),
    (
        "Carvedilol",
        "CC(COC1=CC=CC2=C1C3=CC=CC=C3N2)NCCOC4=CC=CC=C4OC",
        0,
        "LiverTox D",
        "alpha/beta blocker, rare hepatic injury",
    ),
    (
        "Nebivolol",
        "C1CC2=C(C=CC(=C2)F)OC1C(CNCC(C3CCC4=C(O3)C=CC(=C4)F)O)O",
        0,
        "LiverTox E",
        "beta blocker, safe",
    ),
    (
        "Amlodipine",
        "CCOC(=O)C1=C(NC(=C(C1C2=CC=CC=C2Cl)C(=O)OC)C)COCCN",
        0,
        "LiverTox D",
        "CCB, rare hepatic injury",
    ),
    (
        "Lercanidipine",
        "CCOC(=O)C1=C(NC(=C(C1C2=CC(=CC=C2)[N+](=O)[O-])C(=O)OC(C)(C)CN(C)CCC3=CC=CC=C3)C)C",
        0,
        "LiverTox E",
        "CCB, safe",
    ),
    (
        "Felodipine",
        "CC1=C(C(C(=C(N1)C)C(=O)OC)C2=CC(=CC=C2Cl)Cl)C(=O)OCC",
        0,
        "LiverTox D",
        "CCB, rare hepatic injury",
    ),
    (
        "Nifedipine",
        "CC1=C(C(C(=C(N1)C)C(=O)OC)C2=CC=CC=C2[N+](=O)[O-])C(=O)OC",
        0,
        "LiverTox D",
        "CCB, rare hepatic injury",
    ),
    (
        "Nicardipine",
        "CC1=C(C(C(=C(N1)C)C(=O)OCCN(C)CC2=CC=CC=C2)C3=CC(=CC=C3)[N+](=O)[O-])C(=O)OC",
        0,
        "LiverTox D",
        "CCB, rare hepatic injury",
    ),
    (
        "Diltiazem",
        "CC(=O)OC1C(SC2=CC=CC=C2N(C1=O)CCN(C)C)C3=CC=C(C=C3)OC",
        0,
        "LiverTox D",
        "CCB, rare hepatic injury",
    ),
    (
        "Verapamil",
        "CC(C)C(CCCN(C)CCC1=CC(=C(C=C1)OC)OC)(C#N)C2=CC(=C(C=C2)OC)OC",
        0,
        "LiverTox D",
        "CCB, rare hepatic injury",
    ),
    ("Clonidine", "C1CN=C(N1)NC2=C(C=CC=C2Cl)Cl", 0, "LiverTox E", "alpha-2 agonist, safe"),
    ("Moxonidine", "CC1=NC(=NC=C1NC2=NCCN2)OC", 0, "LiverTox E", "alpha-2 agonist, safe"),
    (
        "Doxazosin",
        "CC1=NC2=C(C=C(C=C2C(=N1)N)OC)OC.O=C(N3CCN(CC3)C4=NC5=CC(=C(C=C5N=C4N)OC)OC)C6CCCO6",
        0,
        "LiverTox E",
        "alpha-1 blocker, safe",
    ),
    (
        "Prazosin",
        "COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4=CC=CO4)N)OC",
        0,
        "LiverTox E",
        "alpha-1 blocker, safe",
    ),
    (
        "Terazosin",
        "COC1=C(C=C2C(=C1)C(=NC(=N2)N3CCN(CC3)C(=O)C4CCCO4)N)OC",
        0,
        "LiverTox E",
        "alpha-1 blocker, safe",
    ),
    (
        "Tamsulosin",
        "CCOC1=CC=CC=C1OCCNC(C)CC2=CC(=C(C=C2)OC)S(=O)(=O)N",
        0,
        "LiverTox E",
        "alpha-1 blocker, safe",
    ),
    (
        "Silodosin",
        "CC(CC1=CC2=C(C=C1)N(CC2)CCCOC3=CC=CC=C3C(=O)N)NCCOC4=C(C=C(C=C4)C(F)(F)F)C(=O)N",
        0,
        "LiverTox E",
        "alpha-1 blocker, safe",
    ),
    (
        "Alfuzosin",
        "CC1=NC2=C(C=C(C=C2C(=N1)N)OC)OC.O=C(NCCCN(C)C3=NC4=CC(=C(C=C4N=C3N)OC)OC)C5CCCO5",
        0,
        "LiverTox E",
        "alpha-1 blocker, safe",
    ),
    # --- Other safe drugs ---
    (
        "Acetaminophen",
        "CC(=O)NC1=CC=C(C=C1)O",
        0,
        "LiverTox A but only at overdose",
        "safe at therapeutic doses",
    ),
    ("Aspirin", "CC(=O)OC1=CC=CC=C1C(=O)O", 0, "LiverTox D", "safe at antiplatelet doses"),
    ("Famotidine", "C1=C(SC(=N1)N=C(N)N)CSCCC(=NS(=O)(=O)N)N", 0, "LiverTox E", "H2 blocker, safe"),
    ("Nizatidine", "CC(=NS(=O)(=O)N)NCCSCC1=CC=C(S1)CN(C)C", 0, "LiverTox E", "H2 blocker, safe"),
    ("Roxatidine", "CC(=O)OCCNC(=O)CCOC1=CC(=CC=C1)CN2CCCCC2", 0, "LiverTox E", "H2 blocker, safe"),
    (
        "Ondansetron",
        "CC1=NC=CN1CC2CCC3=C(C2=O)C4=CC=CC=C4N3C",
        0,
        "LiverTox E",
        "5-HT3 antagonist, safe",
    ),
    (
        "Granisetron",
        "CC1=NN(C2=CC=CC=C21)C(=O)NC3CC4CCC(C3)N4C",
        0,
        "LiverTox E",
        "5-HT3 antagonist, safe",
    ),
    (
        "Palonosetron",
        "C1CC2(CCC1N3C=C4CCCCC4=C3C2=O)C5CCN6CCCC6C5",
        0,
        "LiverTox E",
        "5-HT3 antagonist, safe",
    ),
    (
        "Aprepitant",
        "CC(C1=CC(=CC(=C1)C(F)(F)F)C(F)(F)F)OC2C(N(CCO2)CC3=NNC(=O)N3)C4=CC=C(C=C4)F",
        0,
        "LiverTox E",
        "NK1 antagonist, safe",
    ),
    (
        "Cinitapride",
        "CCOC1=C(C=C(C=C1OC)C(=O)NC2CCN(CC2)CCC=C)N",
        0,
        "LiverTox E",
        "prokinetic, safe",
    ),
    (
        "Mosapride",
        "CCN1CCN(CC1)CCNC(=O)C2=C(C=C(C=C2OCC3=CC(=C(C=C3)Cl)F)N)OC",
        0,
        "LiverTox E",
        "prokinetic, safe",
    ),
    (
        "Domperidone",
        "C1=CC=C2C(=C1)NC(=O)N2C3CCN(CC3)CCCN4C=CC5=C4C=CC(=C5)Cl",
        0,
        "LiverTox E",
        "prokinetic, safe",
    ),
    (
        "Loperamide",
        "CC(C)(C(=O)N(C)C)C(C1=CC=CC=C1)(C2=CC=CC=C2)CCN3CCC(CC3)(C4=CC=C(C=C4)Cl)O",
        0,
        "LiverTox E",
        "antidiarrheal, safe",
    ),
    ("Cetirizine_dup", "C1CN(CCN1CCOCC(=O)O)C(C2=CC=CC=C2)C3=CC=C(C=C3)Cl", 0, "DUP", "duplicate"),
    ("Polyethylene glycol", "OCCO", 0, "LiverTox E", "osmotic laxative, safe (placeholder SMILES)"),
    (
        "Lubiprostone",
        "CCCCCC1(CCCCCCC(=O)O)CC(C2(C1CC(C2)=O)O)O",
        0,
        "LiverTox E",
        "ClC-2 activator, safe",
    ),
    ("Linaclotide-like_placeholder", "CC", 0, "EXCLUDED_PEPTIDE", "peptide drug"),
    ("Plecanatide-like_placeholder", "CC", 0, "EXCLUDED_PEPTIDE", "peptide drug"),
    (
        "Eluxadoline",
        "CC(C1=CC=CC=C1OC)NC(=O)C2=CC=CC(=C2)CN(CC3=CC=C(C=C3)C(=O)O)C(=O)C4=NC=C(N4)C",
        0,
        "LiverTox E",
        "mu agonist/delta antagonist, safe",
    ),
    # --- Vitamins, contraceptives, hormones (safe) ---
    (
        "Levothyroxine",
        "N[C@@H](Cc1cc(I)c(Oc2cc(I)c(O)c(I)c2)c(I)c1)C(=O)O",
        0,
        "LiverTox E",
        "thyroid hormone, safe",
    ),
    (
        "Liothyronine",
        "C1=CC(=C(C=C1CC(C(=O)O)N)I)OC2=CC(=C(C(=C2)I)O)I",
        0,
        "LiverTox E",
        "T3 hormone, safe",
    ),
    (
        "Vitamin D3",
        "CC(CCCC(C)C)C1CCC2C1(CCCC2=CC=C3CC(CCC3=C)O)C",
        0,
        "LiverTox E",
        "vitamin D, safe at normal doses",
    ),
    (
        "Calcitriol",
        "CC(CCCC(C)(C)O)C1CCC2C1(CCCC2=CC=C3CC(CC(C3=C)O)O)C",
        0,
        "LiverTox E",
        "active vitamin D, safe",
    ),
    ("Vitamin B6", "CC1=NC=C(C(=C1O)CO)CO", 0, "LiverTox E", "pyridoxine, safe"),
    ("Vitamin B12", "CC", 0, "EXCLUDED_COMPLEX", "complex cofactor, exclude"),
    (
        "Folic acid",
        "C1=CC(=CC=C1C(=O)NC(CCC(=O)O)C(=O)O)NCC2=CN=C3C(=N2)C(=O)NC(=N3)N",
        0,
        "LiverTox E",
        "vitamin B9, safe",
    ),
    (
        "Cholecalciferol",
        "CC(CCCC(C)C)C1CCC2C1(CCCC2=CC=C3CC(CCC3=C)O)C",
        0,
        "DUP",
        "duplicate of vitamin D3",
    ),
    (
        "Ergocalciferol",
        "CC(C=CC(C)C(C)C)C1CCC2C1(CCCC2=CC=C3CC(CCC3=C)O)C",
        0,
        "LiverTox E",
        "vitamin D2, safe",
    ),
    (
        "Levonorgestrel",
        "CCC12CCC3C(C1CCC2(C#C)O)CCC4=CC(=O)CCC34",
        0,
        "LiverTox E",
        "progestin, safe",
    ),
    (
        "Norethindrone",
        "CC12CCC3C(C1CCC2(C#C)O)CCC4=CC(=O)CCC34",
        0,
        "LiverTox E",
        "progestin, safe",
    ),
    (
        "Drospirenone",
        "CC12CCC3C(C1CC4C25CC5C(=O)O4)CCC6=CC(=O)CCC36C",
        0,
        "LiverTox E",
        "progestin, safe at OC doses",
    ),
    (
        "Ethinyl estradiol",
        "CC12CCC3C(C1CCC2(C#C)O)CCC4=C3C=CC(=C4)O",
        0,
        "LiverTox E",
        "estrogen, safe at OC doses",
    ),
    (
        "Estradiol",
        "CC12CCC3C(C1CCC2O)CCC4=C3C=CC(=C4)O",
        0,
        "LiverTox E",
        "estrogen, safe at physiologic doses",
    ),
    (
        "Progesterone",
        "CC(=O)C1CCC2C1(CCC3C2CCC4=CC(=O)CCC34C)C",
        0,
        "LiverTox E",
        "natural progestin, safe",
    ),
    (
        "Medroxyprogesterone",
        "CC(=O)C1(CCC2C1(CC(C3C2CCC4=CC(=O)CCC34C)C)C)OC(=O)C",
        0,
        "LiverTox E",
        "synthetic progestin, safe",
    ),
    (
        "Norgestimate",
        "CCC12CCC3C(C1CCC2(C#C)OC(=O)C)CCC4=CC(=NO)CCC34",
        0,
        "LiverTox E",
        "progestin, safe",
    ),
    (
        "Hydrocortisone",
        "CC12CCC(=O)C=C1CCC3C2C(CC4(C3CCC4(C(=O)CO)O)C)O",
        0,
        "LiverTox E",
        "glucocorticoid, safe at typical doses",
    ),
    (
        "Prednisone",
        "CC12CC(C3(C(C1CCC2(C(=O)CO)O)CCC4=CC(=O)C=CC43C)F)O",
        0,
        "LiverTox B",
        "glucocorticoid, rare hepatic injury at high doses",
    ),
    (
        "Dexamethasone",
        "CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(CC2(C1(C(=O)CO)O)C)O)F)C",
        0,
        "LiverTox D",
        "glucocorticoid, rare hepatic events",
    ),
    (
        "Triamcinolone",
        "CC12CC(C3(C(C1(CC(C2(C(=O)CO)O)O)C)CCC4=CC(=O)C=CC43C)F)O",
        0,
        "LiverTox E",
        "glucocorticoid, safe at typical doses",
    ),
    # --- Misc safe small molecules ---
    (
        "Methimazole",
        "CN1C=CN=C1S",
        0,
        "LiverTox B",
        "antithyroid, hepatotoxic but listed for reference - SWITCH TO POSITIVE",
    ),
    (
        "Propylthiouracil",
        "CCCC1=CC(=O)NC(=S)N1",
        1,
        "LiverTox A",
        "antithyroid with severe hepatic injury - boxed warning",
    ),
    ("Levocarnitine", "CC(C[N+](C)(C)C)CC(=O)[O-]", 0, "LiverTox E", "carnitine supplement, safe"),
    (
        "Pyridostigmine",
        "CN(C)C(=O)OC1=CC=C[N+](=C1)C",
        0,
        "LiverTox E",
        "ACh esterase inhibitor, safe",
    ),
    (
        "Neostigmine",
        "CC[N+](C)(C)C1=CC=CC(=C1)OC(=O)N(C)C",
        0,
        "LiverTox E",
        "ACh esterase inhibitor, safe",
    ),
    (
        "Donepezil",
        "COC1=C(C=C2C(=C1)CC(C2=O)CC3CCN(CC3)CC4=CC=CC=C4)OC",
        0,
        "LiverTox D",
        "AChE inhibitor, rare hepatic injury",
    ),
    ("Rivastigmine", "CCN(C)C(=O)OC1=CC=CC(=C1)C(C)N(C)C", 0, "LiverTox E", "AChE inhibitor, safe"),
    (
        "Galantamine",
        "CN1CCC23C=CC(CC2OC4=C3C1=CC(=C4)OC)O",
        0,
        "LiverTox E",
        "AChE inhibitor, safe",
    ),
    ("Memantine", "CC12CC3CC(C1)CC(C3)(C2)N", 0, "LiverTox E", "NMDA antagonist, safe"),
    # --- Vaccine adjuncts / supplements ---
    (
        "Ferrous sulfate",
        "[Fe+2].[O-]S(=O)(=O)[O-]",
        0,
        "EXCLUDED_INORGANIC",
        "iron supplement, not small molecule",
    ),
    ("Vitamin C", "C(C(C1C(=C(C(=O)O1)O)O)O)O", 0, "LiverTox E", "ascorbic acid, safe"),
    (
        "Vitamin E",
        "CC1=C(C2=C(CCC(O2)(C)CCCC(C)CCCC(C)CCCC(C)C)C(=C1O)C)C",
        0,
        "LiverTox E",
        "tocopherol, safe",
    ),
    (
        "Coenzyme Q10",
        "CC1=C(C(=O)C(=C(C1=O)OC)OC)CC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)C",
        0,
        "LiverTox E",
        "ubiquinone, safe",
    ),
    # --- More antibiotics (safe profile) ---
    (
        "Amoxicillin",
        "CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=C(C=C3)O)N)C(=O)O)C",
        0,
        "LiverTox D",
        "penicillin, hepatic injury mainly with clavulanate",
    ),
    (
        "Ampicillin",
        "CC1(C(N2C(S1)C(C2=O)NC(=O)C(C3=CC=CC=C3)N)C(=O)O)C",
        0,
        "LiverTox D",
        "penicillin, very rare hepatic injury",
    ),
    (
        "Penicillin G",
        "CC1(C(N2C(S1)C(C2=O)NC(=O)CC3=CC=CC=C3)C(=O)O)C",
        0,
        "LiverTox D",
        "natural penicillin, very rare hepatic injury",
    ),
    (
        "Cefuroxime",
        "CON=C(C1=CC=CO1)C(=O)NC2C3N(C2=O)C(=C(CS3)COC(=O)N)C(=O)O",
        0,
        "LiverTox D",
        "second-gen cephalosporin, rare",
    ),
    (
        "Cefepime",
        "CO/N=C(/C(=O)NC1C2SCC(C[N+]3(C)CCCC3)=C(C(=O)[O-])N2C1=O)c1csc(N)n1",
        0,
        "LiverTox D",
        "fourth-gen cephalosporin, rare",
    ),
    (
        "Ceftriaxone",
        "CO/N=C(/C(=O)NC1C2SCC(CSc3nc(=O)c(=O)[nH]n3C)=C(C(=O)O)N2C1=O)c1csc(N)n1",
        0,
        "LiverTox D",
        "third-gen cephalosporin, mostly safe",
    ),
    (
        "Doxycycline",
        "CC1C2=C(C3=C(C(=C1O)O)C(=O)C(=C(C3=O)O)C(=O)N)C(=CC=C2O)O.N(C)C",
        0,
        "LiverTox C",
        "tetracycline, rare hepatic injury",
    ),
    (
        "Azithromycin",
        "CCC1C(C(C(N(CC(CC(C(C(C(C(C(=O)O1)C)OC2CC(C(C(O2)C)O)(C)OC)C)OC3C(C(CC(O3)C)N(C)C)O)(C)O)C)C)C)(C)O)C",
        0,
        "LiverTox C",
        "macrolide, rare hepatic injury",
    ),
    (
        "Clarithromycin",
        "CCC1C(C(C(C(=O)C(CC(C(C(C(C(C(=O)O1)C)OC2CC(C(C(O2)C)O)(C)OC)C)OC3C(C(CC(O3)C)N(C)C)O)(C)O)C)C)(OC)C)C",
        0,
        "LiverTox B",
        "macrolide, rare hepatic injury",
    ),
    (
        "Roxithromycin",
        "CCC1C(C(C(C(=NOCOCCOC)C(CC(C(C(C(C(C(=O)O1)C)OC2CC(C(C(O2)C)O)(C)OC)C)OC3C(C(CC(O3)C)N(C)C)O)(C)O)C)C)O)(C)O",
        0,
        "LiverTox D",
        "macrolide, rare hepatic injury",
    ),
    # ============================================================
    # ADDITIONAL DRUGS - Round 2
    # Newer / less common drugs more likely outside the internal DB
    # ============================================================
    # --- More positive (DILI) drugs ---
    (
        "Acalabrutinib",
        "CC#Cc1cnc(C(=O)N[C@@H]2CCCN2C(=O)C(C)C)c2c1[nH]c(-c1ccc(C(=O)NC)cc1)n2",
        1,
        "LiverTox C",
        "BTK inhibitor with hepatic events",
    ),
    (
        "Zanubrutinib",
        "C=CC(=O)N1CCC[C@@H](n2nc(-c3ccc(Oc4ccccc4)cc3)c3c(N)ncnc32)C1C(N)=O",
        1,
        "LiverTox C",
        "BTK inhibitor with hepatic events",
    ),
    (
        "Ibrutinib",
        "C=CC(=O)N1CCC[C@H](n2nc(-c3ccc(Oc4ccccc4)cc3)c3c(N)ncnc32)C1",
        1,
        "LiverTox B",
        "BTK inhibitor, hepatic injury reported",
    ),
    (
        "Venetoclax",
        "CC1(C)CCC(CN2CCN(c3ccc(C(=O)NS(=O)(=O)c4ccc(NCC5CCOCC5)c([N+](=O)[O-])c4)cc3Oc3cnc4[nH]ccc4c3)CC2)=C(c2ccc(Cl)cc2)C1",
        1,
        "LiverTox C",
        "BCL2 inhibitor with hepatic events",
    ),
    (
        "Ceritinib",
        "CC(C)Oc1cc(Nc2nccc(Nc3ccccc3S(C)(=O)=O)n2)c(C(C)C)cc1C1CCNCC1",
        1,
        "LiverTox B",
        "ALK inhibitor with hepatic injury",
    ),
    (
        "Alectinib",
        "CCc1cc2c(cc1C(=O)N1CCC(N3CCN(C)CC3)CC1)c1cc(C#N)ccc1n2C",
        1,
        "LiverTox B",
        "ALK inhibitor with hepatic injury",
    ),
    (
        "Brigatinib",
        "COc1cc(N2CCC(N3CCN(C)CC3)CC2)c(C)cc1Nc1ncc(Cl)c(-c2ccccc2P(C)(C)=O)n1",
        1,
        "LiverTox C",
        "ALK inhibitor with hepatic events",
    ),
    ("Lorlatinib", "C", 1, "EXCLUDED_COMPLEX", "exclude - macrocycle"),
    (
        "Encorafenib",
        "COC(=O)NC1CC1NS(=O)(=O)c1cccc(F)c1Cn1cc(-c2ncnc(Nc3ccc(Cl)c(C(F)(F)F)c3)n2)c2cccnc12",
        1,
        "LiverTox C",
        "BRAF inhibitor with hepatic events",
    ),
    (
        "Binimetinib",
        "OCCONC(=O)c1cc(F)c2c(c1F)NC(Nc1ccc(I)cc1Br)=NC2",
        1,
        "LiverTox C",
        "MEK inhibitor with hepatic events",
    ),
    (
        "Selumetinib",
        "CN1C=NC2=C1C(NC1=CC=C(Br)C=C1Cl)=C(F)C=C2C(=O)NOCCO",
        1,
        "LiverTox C",
        "MEK inhibitor with hepatic events",
    ),
    (
        "Cobimetinib",
        "OC1(CN2CCC(F)(F)CC2)CC1c1ccc(NC(=O)c2ccc(F)c(I)c2F)cc1F",
        1,
        "LiverTox B",
        "MEK inhibitor with hepatic injury",
    ),
    (
        "Larotrectinib",
        "O=C(c1ccc(F)c(F)c1)N1CCCC1c1ncc(C2CCNCC2)nn1",
        1,
        "LiverTox C",
        "TRK inhibitor with hepatic events",
    ),
    (
        "Entrectinib",
        "CN(C)C(=O)c1ccc(Cl)cc1NC(=O)c1cc(N2CCOCC2)cc(Oc2ccc(F)cc2)c1",
        1,
        "LiverTox C",
        "TRK/ROS1 inhibitor with hepatic events",
    ),
    (
        "Tucatinib",
        "Cc1cc(-c2ncnc3[nH]ccc23)nc(Nc2ccc3c(c2)nc(C(C)(C)C)n3C)n1",
        1,
        "LiverTox C",
        "HER2 TKI with hepatic injury",
    ),
    (
        "Neratinib",
        "Cn1cnc2c1c(/C=C/C(=O)NCC(=O)NC1CCNC1)nc(Nc1ccc(OCc3ccccn3)c(Cl)c1)n2",
        1,
        "LiverTox C",
        "HER2 TKI with hepatic injury",
    ),
    (
        "Tepotinib",
        "CC1=CN(C(=O)C=C1)Cc1ccc(Cn2cnc3c(c2=O)cnc(-c2ccc(CN4CCC(O)(C(F)(F)F)CC4)cc2)c3)cc1",
        1,
        "LiverTox C",
        "MET inhibitor with hepatic injury",
    ),
    (
        "Capmatinib",
        "Cc1nnc(CSc2cnc(C(N)=O)c3cccc(-c4ccc5ncccc5c4F)c23)n1C",
        1,
        "LiverTox C",
        "MET inhibitor with hepatic injury",
    ),
    (
        "Pralsetinib",
        "CC(C)C1=NC=C(C=N1)C1=CC(=NC=N1)NC1=CN(C)N=C1C1CCN(C(=O)C2=CN=CC(F)=C2)CC1",
        1,
        "LiverTox C",
        "RET inhibitor with hepatic events",
    ),
    (
        "Selpercatinib",
        "COC1=CC2=C(N=CC(C3=CN(C)N=C3)=N2)C(=C1)C(C)(C)O",
        1,
        "LiverTox C",
        "RET inhibitor with hepatic events",
    ),
    (
        "Pexidartinib",
        "ClC1=CC2=C(C=C1)N=C(CNC1=NC=C(CC3=CC=NC=C3)C=C1)N2",
        1,
        "LiverTox A",
        "CSF1R inhibitor, boxed warning hepatotoxicity",
    ),
    (
        "Erdafitinib",
        "CCC1=NN(C2=CC=C(N(C)C3=CC=CC(OC)=C3OC)N=C2)C2=CC=NC=C12",
        1,
        "LiverTox C",
        "FGFR inhibitor with hepatic events",
    ),
    (
        "Infigratinib",
        "COC1=CC(NC2=NC=NC3=CC(N4CCN(CC4)CCO)=C(C)C=C23)=CC(OC)=C1Cl",
        1,
        "LiverTox C",
        "FGFR inhibitor with hepatic injury",
    ),
    (
        "Pemigatinib",
        "FC1=C(F)C=C2C(=CC3=CN(C)N=C13)N(C)C(=O)C1=CC2=CC=N1",
        1,
        "LiverTox C",
        "FGFR inhibitor with hepatic injury",
    ),
    (
        "Asciminib",
        "FC1=CC=C(NC2=NC=C(N3C=NC4=CC=CC=C34)C=C2NC(=O)C2=CC=CC(C(F)(F)F)=C2)C=C1Cl",
        1,
        "LiverTox C",
        "BCR-ABL allosteric inhibitor",
    ),
    (
        "Niraparib_dup",
        "C1=CC=C2C(=C1C3=CC(=CC=C3)C4CCCNC4)C=NN2C(=O)N",
        1,
        "DUP",
        "duplicate niraparib",
    ),
    (
        "Talazoparib",
        "CC1=NN2C(C(C(N(C2=N1)C)C3=CC(=C(C=C3F)F)C4=NNC=C4)F)C5=CC=C(C=C5)F",
        1,
        "LiverTox C",
        "PARP inhibitor with hepatic events",
    ),
    (
        "Veliparib",
        "CC(C)(C(=O)N1CCNCC1)C2=NC=CC3=C2NC4=CC=CC=C34",
        1,
        "LiverTox C",
        "PARP inhibitor with hepatic events",
    ),
    (
        "Glasdegib",
        "C1=CC(=CC=C1NC2=CC3=C(N=C2)C(=NN3)C4=NC=CN=C4)C5CCCNC5",
        1,
        "LiverTox C",
        "hedgehog inhibitor with hepatic events",
    ),
    (
        "Gilteritinib",
        "CCC1=CC=C(N=C1)C1=NC(NC2CCN(CC2N(CC)CC)C(C)C)=NC(N2CCC(N)(C(N)=O)CC2)=N1",
        1,
        "LiverTox C",
        "FLT3 inhibitor with hepatic events",
    ),
    (
        "Midostaurin",
        "CC1OC2(O)CC3C4CCC5=C4N(C2C1NC(=O)C1=CC=CC=C1)C1=CC=CC=C1C5=C3C1=C2N(C3=CC=CC=C31)C(=O)N2",
        1,
        "LiverTox B",
        "FLT3 inhibitor with hepatic injury",
    ),
    (
        "Quizartinib",
        "CC(C)(C)C1=NC(=CC=N1)NC(=O)NC1=CC2=C(C=C1)C=CC(OCCN1CCOCC1)=N2",
        1,
        "LiverTox C",
        "FLT3 inhibitor with hepatic events",
    ),
    (
        "Ribociclib",
        "CC(C)N1CC(C)(C)N(C2=CC=C(N=C2)NC2=NC=NC3=CC=CN23)C1=O",
        1,
        "LiverTox B",
        "CDK4/6 inhibitor with hepatic injury",
    ),
    (
        "Palbociclib",
        "CC(=O)C1=C(C)C2=NC(NC3=CC=C(N=C3)N3CCNCC3)=NC=C2N(C2CCCCC2)C1=O",
        1,
        "LiverTox B",
        "CDK4/6 inhibitor with hepatic injury",
    ),
    (
        "Abemaciclib",
        "CCN1CCN(CC2=NC(NC3=NC=C(F)C(C4=CC5=NC(C)=NN5C=C4)=N3)=CC(F)=C2)CC1",
        1,
        "LiverTox B",
        "CDK4/6 inhibitor with hepatic injury",
    ),
    (
        "Trilaciclib",
        "OC1CCN(CC1)CC1=NC2=CN3C(=O)N(C4CCCC4)C4=CC=CC=C4N3C2=N1",
        1,
        "LiverTox C",
        "CDK4/6 inhibitor with hepatic events",
    ),
    (
        "Belinostat",
        "ONC(=O)/C=C/c1cccc(S(=O)(=O)Nc2ccccc2)c1",
        1,
        "LiverTox B",
        "HDAC inhibitor with hepatic injury",
    ),
    (
        "Romidepsin",
        "C[C@@H]1OC(=O)[C@H](C(C)C)NC(=O)C(=C[C@@H](C)CCC(=O)N[C@H](C(=O)N1)CSSC1=CCC1)NC",
        1,
        "LiverTox B",
        "HDAC inhibitor with hepatic injury",
    ),
    (
        "Panobinostat",
        "C[C@H](Cc1ccc(/C=C/C(=O)NO)cc1)NCCc1c[nH]c2ccccc12",
        1,
        "LiverTox B",
        "HDAC inhibitor with hepatic injury",
    ),
    (
        "Vorinostat",
        "ONC(=O)CCCCCCC(=O)Nc1ccccc1",
        1,
        "LiverTox B",
        "HDAC inhibitor with hepatic injury",
    ),
    # --- Newer DILI-positive drugs ---
    (
        "Selinexor",
        "CC(=O)N1N=C(C(F)(F)F)C=C1/C=N/NC(=O)c1cc(-c2cc(C(F)(F)F)cnc2)cn1C",
        1,
        "LiverTox C",
        "XPO1 inhibitor with hepatic events",
    ),
    (
        "Tafamidis",
        "OC(=O)c1cc2nc(-c3ccc(Cl)cc3Cl)oc2cc1",
        1,
        "LiverTox E",
        "TTR stabilizer, safe profile - actually negative",
    ),
    ("Givosiran-like_placeholder", "CC", 1, "EXCLUDED_OLIGO", "siRNA, exclude"),
    ("Inotersen-like_placeholder", "CC", 1, "EXCLUDED_OLIGO", "ASO, exclude"),
    (
        "Voxilaprevir",
        "CC(C)(C)C(=O)NC1CC1c1n[nH]c(=O)c2cc(C3=Cc4ccccc4C3)cc(C3CC3)c12",
        1,
        "LiverTox B",
        "HCV protease inhibitor with hepatic events",
    ),
    (
        "Glecaprevir",
        "FC1=CC=C(N2C=C(C3=CC=CC4=C3N(C2=O)C(C(=O)NS(=O)(=O)C2CC2)CC4)C(=O)NC)C=C1",
        1,
        "LiverTox B",
        "HCV protease inhibitor with hepatic events",
    ),
    ("Pibrentasvir", "C", 1, "EXCLUDED_COMPLEX", "exclude - complex"),
    (
        "Ledipasvir",
        "CC(C)C(NC(=O)OC)C(=O)N1CCCC1c1cc(-c2cc3ccc(-c4cc5c(cn4)C(c4ccccc4)N5C(=O)OC)cc3o2)cc(-c2ccc3c(c2)C(F)C4(F)CCC4c2ccccc23)c1",
        1,
        "LiverTox B",
        "HCV NS5A inhibitor",
    ),
    (
        "Daclatasvir",
        "CCC1=CC(=CN=C1)C1=CC2=C(C=C1)C1=CC=C(C=C1S2)C1=NC(=CN1)C1CCCN1C(=O)C(NC(=O)OC)C(C)C",
        1,
        "LiverTox B",
        "HCV NS5A inhibitor",
    ),
    ("Velpatasvir", "C", 1, "EXCLUDED_COMPLEX", "exclude - complex"),
    (
        "Elbasvir",
        "CC(C)C(NC(=O)OC)C(=O)N1CCCC1c1nc(-c2cc3ccc(-c4cc5ccc(-c6[nH]c(C7CCCN7C(=O)C(NC(=O)OC)C(C)C)nc6-c6ccccc6)cc5o4)cc3o2)c[nH]1",
        1,
        "LiverTox B",
        "HCV NS5A inhibitor",
    ),
    (
        "Grazoprevir",
        "O=C(NS(=O)(=O)C1CC1)C1CC1(NC(=O)C1CC(Oc2nc3ccc4cc5ccccc5cc4c3cc2)CN1C(=O)C(C(C)(C)C)NC(=O)OC)C(=O)OC",
        1,
        "LiverTox B",
        "HCV protease inhibitor",
    ),
    # --- Newer safe drugs ---
    (
        "Apremilast",
        "CCOc1cc(C(C(=O)NCC2=CC=C(C=C2)NS(=O)(=O)C)CS(=O)(=O)C)ccc1OC",
        0,
        "LiverTox D",
        "PDE4 inhibitor, rare hepatic events",
    ),
    (
        "Roflumilast",
        "ClC1=CC(Cl)=CC=C1NC(=O)c1cnccc1OCC1CC1",
        0,
        "LiverTox E",
        "PDE4 inhibitor, safe",
    ),
    (
        "Crisaborole",
        "OB1OCc2cc(Oc3ccc(C#N)cc3)ccc21",
        0,
        "LiverTox E",
        "topical PDE4 inhibitor, safe",
    ),
    (
        "Ozanimod",
        "CCC(NC1=CC=CC=C1)c1cccc(-c2ccc3oc(C(=N)N)nc3c2)c1",
        0,
        "LiverTox D",
        "S1P modulator, rare hepatic events",
    ),
    (
        "Fingolimod",
        "CCCCCCCCc1ccc(CCC(N)(CO)CO)cc1",
        0,
        "LiverTox B",
        "S1P modulator, hepatic events reported",
    ),
    (
        "Siponimod",
        "CC1=CC(=CC=C1OCC(F)(F)F)C(=NOCC(=O)O)CC1=CC=C(N2CC(C(F)(F)F)CC2)C=C1",
        0,
        "LiverTox C",
        "S1P modulator with hepatic events",
    ),
    (
        "Ponesimod",
        "CCCC(C)N(C(=O)c1nc(/N=C/c2ccc(OCC(F)(F)F)c(C(C)(C)C)c2)c(C)s1)C(CO)CO",
        0,
        "LiverTox D",
        "S1P modulator, rare hepatic events",
    ),
    (
        "Cladribine",
        "Nc1nc(Cl)nc2c1ncn2C1CC(O)C(CO)O1",
        0,
        "LiverTox C",
        "purine analog, rare hepatic events",
    ),
    ("Dimethyl fumarate", "COC(=O)/C=C/C(=O)OC", 0, "LiverTox D", "fumarate, rare hepatic events"),
    (
        "Monomethyl fumarate",
        "COC(=O)/C=C/C(=O)O",
        0,
        "LiverTox E",
        "fumarate active metabolite, safe",
    ),
    (
        "Diroximel fumarate",
        "COC(=O)/C=C/C(=O)OCCN1C(=O)CCC1=O",
        0,
        "LiverTox D",
        "fumarate prodrug, rare events",
    ),
    ("Glatiramer-like_placeholder", "CC", 0, "EXCLUDED_PEPTIDE", "peptide"),
    (
        "Teriflunomide_dup",
        "CC(=C(C#N)C(=O)Nc1ccc(C(F)(F)F)cc1)O",
        0,
        "DUP",
        "duplicate teriflunomide",
    ),
    ("Edaravone", "CC1=CC(=O)N(N1)c1ccccc1", 0, "LiverTox E", "free radical scavenger, safe"),
    (
        "Riluzole",
        "Nc1nc2cc(OC(F)(F)F)ccc2s1",
        0,
        "LiverTox B",
        "ALS drug, rare but real hepatic injury",
    ),
    (
        "Pirfenidone",
        "Cc1ccc(=O)n(-c2ccccc2)c1",
        0,
        "LiverTox B",
        "antifibrotic, hepatic injury reported",
    ),
    (
        "Nintedanib",
        "COC(=O)c1ccc2c(c1)C(=O)N(C)/C2=C(\\Nc1ccc(N(C)C(=O)CN2CCN(C)CC2)cc1)c1ccccc1",
        0,
        "LiverTox B",
        "antifibrotic, hepatic injury reported",
    ),
    (
        "Apixaban",
        "COc1ccc(-n2c(C(N)=O)c(C(=O)N(c3ccc(N4CCCCC4=O)cc3)CC)cn2)cc1",
        0,
        "LiverTox D",
        "FXa inhibitor, rare hepatic events",
    ),
    (
        "Rivaroxaban",
        "CN(C(=O)OCC1CN(c2ccc(N3CCOCC3=O)cc2)C1=O)CC1=CC=C(Cl)S1",
        0,
        "LiverTox D",
        "FXa inhibitor, rare hepatic events",
    ),
    (
        "Edoxaban",
        "CN(C)C(=O)C1=CC=C(NC(=O)C2(NC(=O)c3ncc(Cl)s3)CC2)C=C1NS(=O)(=O)c1ccc(C(=O)N2CC[C@H](N(C)C)CC2)cc1",
        0,
        "LiverTox D",
        "FXa inhibitor, rare hepatic events",
    ),
    (
        "Betrixaban",
        "COc1ccc(C(=O)Nc2ccc(C(=N)N(C)C)cc2)cc1NC(=O)c1cnc(Cl)cn1",
        0,
        "LiverTox D",
        "FXa inhibitor, rare hepatic events",
    ),
    (
        "Dabigatran",
        "CCCCCCOC(=O)/N=C(/N)c1ccc(NCc2nc3cc(C(=O)N(CCC(=O)OCC)c4ccccn4)ccc3n2C)cc1",
        0,
        "LiverTox D",
        "thrombin inhibitor, rare hepatic events",
    ),
    (
        "Argatroban",
        "CC1CCCN(S(=O)(=O)c2ccc3ccccc3c2)C1C(=O)NC(CCCN=C(N)N)C(O)c1cccc(C)c1",
        0,
        "LiverTox E",
        "thrombin inhibitor, safe",
    ),
    ("Bivalirudin-like_placeholder", "CC", 0, "EXCLUDED_PEPTIDE", "peptide thrombin inhibitor"),
    (
        "Ticagrelor",
        "CCCSC1N=C(N(C2CCC(O)(CO)C2O)c2ncnc(NC3CC3)c12)NC(=O)C(O)c1ccc(F)c(F)c1",
        0,
        "LiverTox D",
        "P2Y12 antagonist, rare hepatic events",
    ),
    (
        "Cangrelor",
        "OC1C(O)C(N2C=NC3=C2N=C(SCCCC(F)(F)F)N(CC(F)(F)Cl)C3=O)OC1COP(=O)(O)OP(=O)(O)OP(=O)(O)O",
        0,
        "LiverTox E",
        "P2Y12 antagonist, safe",
    ),
    (
        "Vorapaxar",
        "CC(=O)NC1CC2(CCC(C=C2)C(=O)OCC)C(C1c1ccc(/C=C/c2ncc(F)cc2)cc1)C(=O)NC",
        0,
        "LiverTox E",
        "PAR1 antagonist, safe",
    ),
    # --- More older safe drugs ---
    ("Bupivacaine", "CCCCN1CCCCC1C(=O)Nc1c(C)cccc1C", 0, "LiverTox E", "local anesthetic, safe"),
    ("Lidocaine", "CCN(CC)CC(=O)Nc1c(C)cccc1C", 0, "LiverTox E", "local anesthetic, safe"),
    ("Ropivacaine", "CCCN1CCCCC1C(=O)Nc1c(C)cccc1C", 0, "LiverTox E", "local anesthetic, safe"),
    ("Mepivacaine", "CN1CCCCC1C(=O)Nc1c(C)cccc1C", 0, "LiverTox E", "local anesthetic, safe"),
    ("Articaine", "CCCNC(C)C(=O)Nc1sc(C)c(C(=O)OC)c1C", 0, "LiverTox E", "local anesthetic, safe"),
    ("Prilocaine", "CCCNC(C)C(=O)Nc1cccc(C)c1", 0, "LiverTox E", "local anesthetic, safe"),
    ("Etidocaine", "CCCN(CC)C(CC)C(=O)Nc1c(C)cccc1C", 0, "LiverTox E", "local anesthetic, safe"),
    ("Tetracaine", "CCCCNc1ccc(C(=O)OCCN(C)C)cc1", 0, "LiverTox E", "local anesthetic, safe"),
    ("Benzocaine", "CCOC(=O)c1ccc(N)cc1", 0, "LiverTox E", "local anesthetic, safe"),
    ("Procaine", "CCN(CC)CCOC(=O)c1ccc(N)cc1", 0, "LiverTox E", "local anesthetic, safe"),
    ("Pramoxine", "CCCCOc1ccc(OCCCN2CCOCC2)cc1", 0, "LiverTox E", "local anesthetic, safe"),
    ("Dyclonine", "CCCCNc1ccccc1C(=O)CCc1ccc(OCCCC)cc1", 0, "LiverTox E", "local anesthetic, safe"),
    # --- More positive (lesser-known) ---
    (
        "Phenazopyridine",
        "Nc1ccc(N=Nc2ccccc2N)nc1N",
        1,
        "LiverTox D",
        "urinary analgesic with hepatic injury",
    ),
    (
        "Chlorzoxazone",
        "ClC1=CC2=C(NC(=O)O2)C=C1",
        1,
        "LiverTox B",
        "muscle relaxant with hepatic injury",
    ),
    (
        "Carisoprodol",
        "CCCC(C)(COC(N)=O)COC(=O)NC(C)C",
        1,
        "LiverTox C",
        "muscle relaxant, hepatic injury",
    ),
    (
        "Methocarbamol",
        "COc1ccccc1OCC(O)COC(N)=O",
        0,
        "LiverTox D",
        "muscle relaxant, rare hepatic injury",
    ),
    (
        "Tizanidine",
        "ClC1=CC2=C(C=C1)SC(=N2)N=C1NCCN1",
        1,
        "LiverTox B",
        "alpha-2 agonist muscle relaxant, hepatic injury",
    ),
    ("Baclofen", "NCC(CC(=O)O)c1ccc(Cl)cc1", 0, "LiverTox D", "GABA analog, rare hepatic injury"),
    (
        "Cyclobenzaprine",
        "CN(C)CC/C=C1\\c2ccccc2C=Cc2ccccc21",
        0,
        "LiverTox E",
        "muscle relaxant, safe",
    ),
    ("Eperisone", "CCC1CCCN1CC(=O)c1ccc(C)cc1", 0, "LiverTox E", "muscle relaxant, safe"),
    ("Mexiletine", "CC(CN)Oc1c(C)cccc1C", 0, "LiverTox D", "antiarrhythmic, rare hepatic injury"),
    (
        "Flecainide",
        "CC1NCC1CONc1cc(C(F)(F)F)c(OCC(F)(F)F)cc1C(F)(F)F",
        0,
        "LiverTox D",
        "antiarrhythmic, rare hepatic injury",
    ),
    (
        "Propafenone",
        "CCCNCC(O)COc1ccccc1C(=O)CCc1ccccc1",
        0,
        "LiverTox B",
        "antiarrhythmic with hepatic injury",
    ),
    (
        "Quinidine",
        "C=CC1CN2CCC1CC2C(O)c1ccnc2ccc(OC)cc12",
        1,
        "LiverTox B",
        "antiarrhythmic with hepatic injury",
    ),
    (
        "Procainamide",
        "CCN(CC)CCNC(=O)c1ccc(N)cc1",
        0,
        "LiverTox C",
        "antiarrhythmic, rare hepatic injury",
    ),
    # --- More antidepressants/CNS ---
    (
        "Trazodone",
        "Clc1cccc(N2CCN(CCCn3nc4ccccc4n3)CC2)c1",
        0,
        "LiverTox D",
        "antidepressant, rare hepatic injury",
    ),
    ("Duloxetine", "CNCCC(c1cccs1)Oc1cccc2ccccc12", 1, "LiverTox B", "SNRI with hepatic injury"),
    ("Atomoxetine", "CC(Cc1ccccc1Oc1ccccc1)NC", 1, "LiverTox B", "NRI with hepatic injury"),
    ("Reboxetine", "CCOc1ccccc1OC(C1CCOC1)c1ccccc1", 0, "LiverTox E", "NRI, safe"),
    (
        "Citalopram",
        "N#Cc1ccc2c(c1)C(c1ccc(F)cc1)(CCCN(C)C)OC2",
        0,
        "LiverTox D",
        "SSRI, rare hepatic injury",
    ),
    (
        "Escitalopram",
        "N#Cc1ccc2c(c1)[C@](c1ccc(F)cc1)(CCCN(C)C)OC2",
        0,
        "LiverTox D",
        "SSRI, rare hepatic injury",
    ),
    (
        "Sertraline",
        "CN[C@H]1CC[C@@H](c2ccc(Cl)c(Cl)c2)c2ccccc21",
        1,
        "LiverTox B",
        "SSRI with hepatic injury",
    ),
    (
        "Paroxetine",
        "Fc1ccc([C@@H]2CCN[C@@H]2COc2ccc3OCOc3c2)cc1",
        1,
        "LiverTox C",
        "SSRI with hepatic injury",
    ),
    (
        "Fluvoxamine",
        "CCCCO/N=C(/CCCC1=CC=C(C(F)(F)F)C=C1)CCN",
        1,
        "LiverTox C",
        "SSRI with hepatic injury",
    ),
    (
        "Fluoxetine",
        "CNCC[C@H](Oc1ccc(C(F)(F)F)cc1)c1ccccc1",
        1,
        "LiverTox C",
        "SSRI, rare hepatic injury",
    ),
    ("Imipramine", "CN(C)CCCN1c2ccccc2CCc2ccccc21", 0, "LiverTox B", "TCA with hepatic injury"),
    (
        "Amitriptyline",
        "CN(C)CC/C=C1\\c2ccccc2CCc2ccccc21",
        0,
        "LiverTox B",
        "TCA with hepatic injury",
    ),
    ("Nortriptyline", "CNCC/C=C1\\c2ccccc2CCc2ccccc21", 0, "LiverTox B", "TCA with hepatic injury"),
    (
        "Clomipramine",
        "CN(C)CCCN1c2ccccc2CCc2cc(Cl)ccc21",
        0,
        "LiverTox B",
        "TCA with hepatic injury",
    ),
    ("Doxepin", "CN(C)CC/C=C1/c2ccccc2COc2ccccc21", 0, "LiverTox D", "TCA, rare hepatic injury"),
    (
        "Maprotiline",
        "CNCCCC12CCC(c3ccccc31)c1ccccc12",
        0,
        "LiverTox C",
        "tetracyclic antidepressant",
    ),
    ("Bupropion_dup", "CC(C(=O)c1cccc(Cl)c1)NC(C)(C)C", 0, "DUP", "duplicate"),
    # --- Misc additional safe / positive ---
    (
        "Levocarbidopa",
        "C(=O)O[C@@H](Cc1ccc(O)c(O)c1)C(C)(N)N",
        0,
        "LiverTox E",
        "DOPA decarboxylase inhibitor, safe",
    ),
    ("Pramipexole", "CCCNC1CCc2nc(N)sc2C1", 0, "LiverTox E", "dopamine agonist, safe"),
    ("Ropinirole", "CCCN(CCC)CCc1ccc2c(c1)CC(=O)N2", 0, "LiverTox E", "dopamine agonist, safe"),
    (
        "Rasagiline",
        "C#CCN[C@H]1CCc2ccccc21",
        0,
        "LiverTox D",
        "MAO-B inhibitor, rare hepatic injury",
    ),
    (
        "Selegiline",
        "C#CCN(C)[C@H](C)Cc1ccccc1",
        0,
        "LiverTox D",
        "MAO-B inhibitor, rare hepatic injury",
    ),
    (
        "Safinamide",
        "Cc1ccc(OCc2ccc(F)cc2)cc1CC(NC(C)C(N)=O)C",
        0,
        "LiverTox D",
        "MAO-B inhibitor, rare hepatic events",
    ),
    (
        "Entacapone",
        "CCN(CC)C(=O)/C(=C/c1cc(O)c(O)c(N(=O)=O)c1)C#N",
        0,
        "LiverTox D",
        "COMT inhibitor, rare hepatic injury",
    ),
    (
        "Opicapone",
        "[O-][N+](=O)c1cc(/C=C/c2ccccc2)oc1Oc1cc(Cl)c(Cl)cc1Cl",
        0,
        "LiverTox E",
        "COMT inhibitor, safe profile",
    ),
    ("Amantadine", "NC12CC3CC(C1)CC(C3)C2", 0, "LiverTox E", "antiviral/anti-Parkinson, safe"),
    ("Rimantadine", "CC(N)C12CC3CC(C1)CC(C3)C2", 0, "LiverTox E", "antiviral, safe"),
    (
        "Oseltamivir",
        "CCOC(=O)C1=C[C@H](OC(CC)CC)[C@@H](NC(C)=O)[C@H](N)C1",
        0,
        "LiverTox D",
        "neuraminidase inhibitor, rare hepatic injury",
    ),
    (
        "Zanamivir",
        "CC(=O)N[C@@H]1C=C(C(=O)O)O[C@H]([C@@H](O)[C@@H](O)CO)[C@H]1N=C(N)N",
        0,
        "LiverTox E",
        "neuraminidase inhibitor, safe",
    ),
    (
        "Peramivir",
        "CC(=O)N[C@@H]1[C@H](N=C(N)N)C[C@H](C(=O)O)[C@@H]1C(C)CC",
        0,
        "LiverTox E",
        "neuraminidase inhibitor, safe",
    ),
    (
        "Baloxavir",
        "Cc1cnc2c(c1)c1cc(F)c(F)cc1C2=NN[C@@H]1OCCN(C(=O)CN2N=CC=CC2=O)C1",
        0,
        "LiverTox E",
        "cap-endonuclease inhibitor, safe",
    ),
    (
        "Remdesivir",
        "CCC(CC)COC(=O)[C@H](C)N[P@@](=O)(OC[C@H]1O[C@](C#N)([C@H](O)[C@@H]1O)c1ccc2c(N)ncnn12)Oc1ccccc1",
        0,
        "LiverTox B",
        "antiviral with hepatic injury",
    ),
    (
        "Molnupiravir",
        "CC(C)C(=O)OC[C@H]1O[C@@H](N2C=C\\C(=N\\O)NC2=O)[C@H](O)[C@@H]1O",
        0,
        "LiverTox D",
        "antiviral, rare hepatic events",
    ),
    (
        "Nirmatrelvir",
        "CC1([C@@H]2CC1)[C@H](N(C(=O)[C@H](NC(=O)C(F)(F)F)C(C)(C)C)C(=O)C[C@H]2c1cccnc1)C#N",
        0,
        "LiverTox E",
        "SARS-CoV-2 protease inhibitor, safe",
    ),
    (
        "Daridorexant",
        "ClC1=CC=CC(C(=O)N2CCC(N3CCN4N=C(C)C(C)=CC4=C3)CC2)=C1OC",
        0,
        "LiverTox E",
        "orexin antagonist, safe",
    ),
    (
        "Suvorexant",
        "ClC1=CC=NC2=C1C=NN2C1CCN(C(=O)C2(C)C=CC=CC2)CC1",
        0,
        "LiverTox D",
        "orexin antagonist, rare hepatic events",
    ),
    (
        "Lemborexant",
        "Cc1nc(C2CCN(C(=O)C(C)C)CC2)ccc1NC(=O)c1ccc(F)cc1F",
        0,
        "LiverTox D",
        "orexin antagonist, rare hepatic events",
    ),
    (
        "Tasimelteon",
        "CC1=CC=CC2=C1[C@@H](C(=O)CCC1CC1)C1CCC12",
        0,
        "LiverTox E",
        "melatonin agonist, safe",
    ),
    (
        "Ramelteon",
        "CC(=O)NCC[C@H]1CCC2=C1C1=C(O2)CCC1",
        0,
        "LiverTox D",
        "melatonin agonist, rare hepatic injury",
    ),
    (
        "Agomelatine",
        "COc1ccc2cc(CCNC(C)=O)ccc2c1",
        1,
        "LiverTox B",
        "melatonin agonist with hepatic injury",
    ),
    (
        "Lurasidone",
        "O=C1N2CCCC[C@@H]2C(=O)N1C[C@@H]1CCCC[C@H]1CN1CCN(c2nsc3ccccc23)CC1",
        0,
        "LiverTox E",
        "antipsychotic, safe",
    ),
    (
        "Iloperidone",
        "CCOc1cc(F)ccc1OCCCN1CCC(c2noc3cc(F)ccc23)CC1",
        0,
        "LiverTox D",
        "antipsychotic, rare hepatic events",
    ),
    (
        "Asenapine",
        "Cl[CH3+]N1C[C@@H]2[C@@H](C1)c1ccc(Cl)cc1Oc1ccccc1-2",
        0,
        "LiverTox D",
        "antipsychotic, rare hepatic events",
    ),
    (
        "Cariprazine",
        "CCN(CC)CCNC(=O)NC1CCC(N2CCN(c3cc(Cl)ccc3Cl)CC2)CC1",
        0,
        "LiverTox D",
        "antipsychotic, rare hepatic events",
    ),
    (
        "Brexpiprazole",
        "O=C1CC2=CC=CC=C2N1CCCCOC1=CC=C2N=C(N3CCN(CC4=CC=CC5=C4SC=C5)CC3)C=CC2=C1",
        0,
        "LiverTox D",
        "antipsychotic, rare hepatic events",
    ),
    (
        "Aripiprazole",
        "Clc1cccc(Cl)c1N1CCN(CCCCOc2ccc3c(c2)CCC(=O)N3)CC1",
        0,
        "LiverTox D",
        "antipsychotic, rare hepatic injury",
    ),
    (
        "Pimavanserin",
        "CC(C)COCC1=CC=C(C(=N1)CNC(=O)C2=CC=C(C=C2)CN3CCC(CC3)NC(=O)OC(C)(C)C)F",
        0,
        "LiverTox D",
        "5HT2A inverse agonist",
    ),
    (
        "Valbenazine",
        "CC(C)CC(=O)O[C@@H]1[C@@H]2CN3CCc4cc(OC)c(OC)cc4[C@@H]3C[C@@H]2CC(C)C1",
        0,
        "LiverTox D",
        "VMAT2 inhibitor, rare hepatic events",
    ),
    (
        "Tetrabenazine",
        "CC(C)CC1CN2CCc3cc(OC)c(OC)cc3C2CC1=O",
        0,
        "LiverTox D",
        "VMAT2 inhibitor, rare hepatic events",
    ),
    (
        "Deutetrabenazine",
        "[2H]C([2H])([2H])Oc1cc2c(cc1OC([2H])([2H])[2H])C1CC(=O)C(CC(C)C)CN1CC2",
        0,
        "LiverTox D",
        "deuterated tetrabenazine",
    ),
    # --- Cholesterol meds ---
    (
        "Atorvastatin",
        "CC(C)c1c(C(=O)Nc2ccccc2)c(-c2ccccc2)c(-c2ccc(F)cc2)n1CC[C@@H](O)C[C@@H](O)CC(=O)O",
        0,
        "LiverTox B",
        "statin, hepatic injury reported",
    ),
    (
        "Rosuvastatin",
        "CC(C)c1nc(N(C)S(C)(=O)=O)nc(-c2ccc(F)cc2)c1/C=C/[C@@H](O)C[C@@H](O)CC(=O)O",
        0,
        "LiverTox B",
        "statin, hepatic injury reported",
    ),
    (
        "Pitavastatin",
        "OC(=O)C[C@H](O)C[C@H](O)/C=C/c1c(C2CC2)nc2ccccc2c1-c1ccc(F)cc1",
        0,
        "LiverTox B",
        "statin, hepatic injury reported",
    ),
    (
        "Simvastatin",
        "CCC(C)(C)C(=O)OC1CC(C)C=C2C=CC(C)C(CCC3CC(O)CC(=O)O3)C12",
        0,
        "LiverTox B",
        "statin, hepatic injury reported",
    ),
    (
        "Pravastatin",
        "CCC(C)C(=O)OC1CC(O)C=C2C=CC(C)C(CCC(O)CC(O)CC(=O)O)C12",
        0,
        "LiverTox D",
        "statin, rare hepatic injury",
    ),
    (
        "Lovastatin",
        "CCC(C)C(=O)OC1CC(C)C=C2C=CC(C)C(CCC3CC(O)CC(=O)O3)C12",
        0,
        "LiverTox B",
        "statin, hepatic injury reported",
    ),
    (
        "Fluvastatin",
        "CC(C)n1c2ccccc2c(-c2ccc(F)cc2)c1/C=C/C(O)CC(O)CC(=O)O",
        0,
        "LiverTox B",
        "statin, hepatic injury reported",
    ),
    (
        "Ezetimibe",
        "OC(c1ccc(F)cc1)C[C@H]1[C@@H](c2ccc(O)cc2)N(c2ccc(F)cc2)C1=O",
        0,
        "LiverTox D",
        "cholesterol absorption inhibitor, rare events",
    ),
    (
        "Bempedoic acid",
        "CC(CCCCCCC(C)(C)C(=O)O)(CCCCCC(O)=O)CO",
        0,
        "LiverTox E",
        "ATP citrate lyase inhibitor, safe",
    ),
    ("Inclisiran-like_placeholder", "CC", 0, "EXCLUDED_OLIGO", "siRNA"),
    (
        "Lomitapide_dup",
        "C1CCN(CC1)CC2=CC=C(C=C2)CCCCC3(CCCCN3C(=O)NC4=CC=C(C=C4)C(F)(F)F)C(=O)NCC(F)(F)F",
        1,
        "DUP",
        "duplicate lomitapide",
    ),
    (
        "Gemfibrozil",
        "CC(C)(CCCOc1ccc(C)cc1C)C(=O)O",
        0,
        "LiverTox C",
        "fibrate, rare hepatic injury",
    ),
    (
        "Fenofibrate",
        "CC(C)OC(=O)C(C)(C)Oc1ccc(C(=O)c2ccc(Cl)cc2)cc1",
        0,
        "LiverTox B",
        "fibrate, hepatic injury reported",
    ),
    # --- Antibiotics & more ---
    (
        "Clindamycin",
        "CCCC1CC(C(=O)NC(C(=O)N(C)C)C(Cl)CC)N(C)C1C(C(O)C(O)C(SC)O)O",
        0,
        "LiverTox B",
        "lincosamide, rare hepatic injury",
    ),
    ("Vancomycin", "C", 0, "EXCLUDED_COMPLEX", "exclude - macrocyclic glycopeptide"),
    (
        "Metronidazole",
        "Cc1ncc([N+](=O)[O-])n1CCO",
        0,
        "LiverTox D",
        "antimicrobial, rare hepatic injury",
    ),
    ("Tinidazole", "CCS(=O)(=O)CCn1c(C)ncc1[N+](=O)[O-]", 0, "LiverTox E", "antimicrobial, safe"),
    ("Ornidazole", "Cc1ncc([N+](=O)[O-])n1CC(O)CCl", 0, "LiverTox E", "antimicrobial, safe"),
    (
        "Albendazole",
        "CCCSC1=NC2=CC(NC(=O)OC)=CC=C2N1",
        1,
        "LiverTox B",
        "antiparasitic with hepatic injury",
    ),
    (
        "Mebendazole",
        "COC(=O)Nc1nc2cc(C(=O)c3ccccc3)ccc2[nH]1",
        1,
        "LiverTox C",
        "antiparasitic with hepatic injury",
    ),
    (
        "Praziquantel",
        "O=C1N2CCN(C(=O)C3CCCCC3)CC2c2ccccc21",
        0,
        "LiverTox D",
        "antiparasitic, rare hepatic injury",
    ),
    (
        "Ivermectin",
        "CCC(C)C1OC2(CC1C)CC1C(=CC(=O)O1)CC2CC1OC2(OC(=O)CC2C(C)C1C)C(C)C",
        0,
        "LiverTox D",
        "antiparasitic, rare hepatic injury",
    ),
    ("Pyrantel", "Cc1cccc(/C=C/c2nc(O)[nH]n2)c1", 0, "LiverTox E", "antiparasitic, safe"),
    (
        "Atovaquone",
        "C(C1=C(O)C(=O)C2=CC=CC=C2C1=O)1CCC(c2ccc(Cl)cc2)CC1",
        0,
        "LiverTox D",
        "antimalarial, rare hepatic injury",
    ),
    ("Proguanil", "ClC1=CC=C(NC(=NC(N)=N)NC(C)C)C=C1", 0, "LiverTox E", "antimalarial, safe"),
    (
        "Mefloquine",
        "OC(c1ccnc2c1cc(C(F)(F)F)cc2C(F)(F)F)C1CCCCN1",
        0,
        "LiverTox C",
        "antimalarial, rare hepatic injury",
    ),
    (
        "Primaquine",
        "CC(CCCN)NC1=CC=NC2=CC(OC)=CC=C12",
        0,
        "LiverTox D",
        "antimalarial, rare hepatic injury",
    ),
    (
        "Chloroquine",
        "CCN(CC)CCCC(C)Nc1ccnc2cc(Cl)ccc12",
        1,
        "LiverTox C",
        "antimalarial with hepatic injury",
    ),
    (
        "Hydroxychloroquine",
        "CCN(CCO)CCCC(C)Nc1ccnc2cc(Cl)ccc12",
        1,
        "LiverTox C",
        "antimalarial with hepatic injury",
    ),
    (
        "Artemether",
        "CC1CCC2C(C)C(=O)OC3OC4(C)CCC1C23OO4",
        0,
        "LiverTox D",
        "antimalarial, rare hepatic injury",
    ),
    (
        "Artesunate",
        "CC1CCC2C(C)C(=O)OC3OC4(C)CCC1C23OO4.OC(=O)CCC(=O)O",
        0,
        "LiverTox D",
        "antimalarial, rare hepatic injury",
    ),
    # ============================================================
    # End of list
    # ============================================================
]


def calc_inchi_key(smiles: str) -> str | None:
    """Return InChIKey or None if RDKit fails."""
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None
        return Chem.MolToInchiKey(mol)
    except Exception:
        return None


def canonical_smiles(smiles: str) -> str | None:
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None
        return Chem.MolToSmiles(mol, canonical=True)
    except Exception:
        return None


def main() -> None:
    repo_root = Path("/Users/parkjeong-uk/CODING/2026/school/Bioinformatics")
    db_path = repo_root / "data" / "labels_db" / "full.parquet"
    out_path = repo_root / "data" / "sanity_v2" / "external_sanity_200.csv"

    db = pd.read_parquet(db_path)
    db_keys: set[str] = set(db["inchi_key"].dropna().astype(str).tolist())
    print(f"DB inchi_keys: {len(db_keys)}")

    rows = []
    smiles_parse_fail = 0
    excluded_marker = 0
    for name, smi, label, ref, reason in DRUGS:
        if ref.startswith("EXCLUDED") or ref == "DUP":
            excluded_marker += 1
            continue
        canon = canonical_smiles(smi)
        ikey = calc_inchi_key(smi)
        if ikey is None or canon is None:
            smiles_parse_fail += 1
            continue
        rows.append(
            {
                "name": name,
                "smiles": smi,
                "canonical_smiles": canon,
                "inchi_key": ikey,
                "label": label,
                "reference": ref,
                "reasoning": reason,
            }
        )

    df = pd.DataFrame(rows)
    print(
        f"Parsed: {len(df)}, excluded markers: {excluded_marker}, parse_fail: {smiles_parse_fail}"
    )

    # Deduplicate by inchi_key (keep first)
    before = len(df)
    df = df.drop_duplicates(subset=["inchi_key"], keep="first").reset_index(drop=True)
    print(f"After dedup within list: {len(df)} (removed {before - len(df)} duplicates)")

    # Filter against DB
    df["in_db"] = df["inchi_key"].isin(db_keys)
    in_db_pos = int(((df["label"] == 1) & df["in_db"]).sum())
    in_db_neg = int(((df["label"] == 0) & df["in_db"]).sum())
    external = df[~df["in_db"]].drop(columns=["in_db"]).reset_index(drop=True)

    print(f"In DB: pos={in_db_pos}, neg={in_db_neg}")
    print(f"External (kept): {len(external)}")
    print(f"  pos: {(external['label'] == 1).sum()}")
    print(f"  neg: {(external['label'] == 0).sum()}")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    external.to_csv(out_path, index=False)
    print(f"Wrote: {out_path}")


if __name__ == "__main__":
    main()
